import enum, uuid
from datetime import date, datetime, time, timezone
from decimal import Decimal
from sqlalchemy import String, Date, DateTime, Time, ForeignKey, Text, Numeric, Boolean, Enum, Float, JSON, LargeBinary, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column, relationship as orm_relationship
from app.db.base import Base

def uid(): return str(uuid.uuid4())
def now(): return datetime.now(timezone.utc)
class Role(str, enum.Enum): PROFESSIONAL="professional"; FAMILY="family"; ADMIN="admin"
class VisitStatus(str, enum.Enum): SCHEDULED="scheduled"; COMPLETED="completed"; CANCELED="canceled"
class SubscriptionStatus(str, enum.Enum): TRIAL="trial"; ACTIVE="active"; PAST_DUE="past_due"; CANCELED="canceled"
class BillingCycle(str, enum.Enum): MONTHLY="monthly"; ANNUAL="annual"
class TenantMixin:
    organization_id: Mapped[str] = mapped_column(ForeignKey("organizations.id"), index=True)
class TimeMixin:
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=now)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=now, onupdate=now)
class Organization(Base, TimeMixin):
    __tablename__="organizations"; id: Mapped[str]=mapped_column(String(36), primary_key=True, default=uid); name: Mapped[str]=mapped_column(String(120))
class User(Base, TenantMixin, TimeMixin):
    __tablename__="users"; id: Mapped[str]=mapped_column(String(36), primary_key=True, default=uid); name: Mapped[str]=mapped_column(String(120)); email: Mapped[str]=mapped_column(String(255), unique=True, index=True); password_hash: Mapped[str]=mapped_column(String(255)); role: Mapped[Role]=mapped_column(Enum(Role)); is_active: Mapped[bool]=mapped_column(Boolean, default=True); email_verified_at: Mapped[datetime | None]=mapped_column(DateTime(timezone=True), nullable=True); last_login_at: Mapped[datetime | None]=mapped_column(DateTime(timezone=True), nullable=True); default_session_duration_minutes: Mapped[int]=mapped_column(default=60); phone: Mapped[str | None]=mapped_column(String(30), nullable=True); cpf: Mapped[str | None]=mapped_column(String(14), nullable=True); profession: Mapped[str | None]=mapped_column(String(60), nullable=True); profession_other: Mapped[str | None]=mapped_column(String(100), nullable=True); council_name: Mapped[str | None]=mapped_column(String(30), nullable=True); council_code: Mapped[str | None]=mapped_column(String(40), nullable=True); council_state: Mapped[str | None]=mapped_column(String(2), nullable=True); postal_code: Mapped[str | None]=mapped_column(String(9), nullable=True); address: Mapped[str | None]=mapped_column(String(255), nullable=True); address_number: Mapped[str | None]=mapped_column(String(20), nullable=True); address_complement: Mapped[str | None]=mapped_column(String(100), nullable=True); neighborhood: Mapped[str | None]=mapped_column(String(100), nullable=True); city: Mapped[str | None]=mapped_column(String(100), nullable=True); state: Mapped[str | None]=mapped_column(String(2), nullable=True); lgpd_consent_at: Mapped[datetime]=mapped_column(DateTime(timezone=True), default=now)
    profile_photo: Mapped[bytes | None]=mapped_column(LargeBinary,nullable=True); profile_photo_content_type: Mapped[str | None]=mapped_column(String(40),nullable=True); profile_photo_updated_at: Mapped[datetime | None]=mapped_column(DateTime(timezone=True),nullable=True)
    professional_summary: Mapped[str | None]=mapped_column(Text,nullable=True); specialties: Mapped[str | None]=mapped_column(Text,nullable=True); education: Mapped[str | None]=mapped_column(Text,nullable=True); experience_years: Mapped[int | None]=mapped_column(nullable=True); service_areas: Mapped[str | None]=mapped_column(Text,nullable=True); professional_approach: Mapped[str | None]=mapped_column(Text,nullable=True); signature_name: Mapped[str | None]=mapped_column(String(120),nullable=True); signature_council: Mapped[str | None]=mapped_column(String(100),nullable=True); signature_profession: Mapped[str | None]=mapped_column(String(100),nullable=True)
    registration_source: Mapped[str | None]=mapped_column(String(40),nullable=True); first_access_at: Mapped[datetime | None]=mapped_column(DateTime(timezone=True),nullable=True); first_patient_at: Mapped[datetime | None]=mapped_column(DateTime(timezone=True),nullable=True); first_schedule_at: Mapped[datetime | None]=mapped_column(DateTime(timezone=True),nullable=True); first_record_at: Mapped[datetime | None]=mapped_column(DateTime(timezone=True),nullable=True); activated_at: Mapped[datetime | None]=mapped_column(DateTime(timezone=True),nullable=True); first_paid_at: Mapped[datetime | None]=mapped_column(DateTime(timezone=True),nullable=True)
    email_operational: Mapped[bool]=mapped_column(Boolean,default=True); email_guidance: Mapped[bool]=mapped_column(Boolean,default=True); email_billing: Mapped[bool]=mapped_column(Boolean,default=True); email_marketing: Mapped[bool]=mapped_column(Boolean,default=False); whatsapp_allowed: Mapped[bool]=mapped_column(Boolean,default=False); communication_consent_at: Mapped[datetime | None]=mapped_column(DateTime(timezone=True),nullable=True); communication_consent_source: Mapped[str | None]=mapped_column(String(40),nullable=True); communication_consent_version: Mapped[str | None]=mapped_column(String(20),nullable=True)
class ProfessionalAvailability(Base, TenantMixin, TimeMixin):
    __tablename__="professional_availabilities"; id: Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); professional_id: Mapped[str]=mapped_column(ForeignKey("users.id"),index=True); weekday: Mapped[int]=mapped_column(index=True); start_time: Mapped[time]=mapped_column(Time); end_time: Mapped[time]=mapped_column(Time); is_active: Mapped[bool]=mapped_column(Boolean,default=True)
class GoogleIdentity(Base, TimeMixin):
    __tablename__="google_identities"
    id: Mapped[str]=mapped_column(String(36),primary_key=True,default=uid)
    user_id: Mapped[str]=mapped_column(ForeignKey("users.id"),unique=True,index=True)
    subject: Mapped[str]=mapped_column(String(255),unique=True,index=True)
class Patient(Base, TenantMixin, TimeMixin):
    __tablename__="patients"; id: Mapped[str]=mapped_column(String(36), primary_key=True, default=uid); name: Mapped[str]=mapped_column(String(120)); status: Mapped[str]=mapped_column(String(20),default="active",index=True); cpf: Mapped[str | None]=mapped_column(String(14), nullable=True); birth_date: Mapped[date | None]=mapped_column(Date, nullable=True); gender: Mapped[str | None]=mapped_column(String(30), nullable=True); phone: Mapped[str | None]=mapped_column(String(30), nullable=True); email: Mapped[str | None]=mapped_column(String(255), nullable=True); postal_code: Mapped[str | None]=mapped_column(String(9), nullable=True); address: Mapped[str | None]=mapped_column(String(255), nullable=True); address_number: Mapped[str | None]=mapped_column(String(20), nullable=True); address_complement: Mapped[str | None]=mapped_column(String(100), nullable=True); neighborhood: Mapped[str | None]=mapped_column(String(100), nullable=True); city: Mapped[str | None]=mapped_column(String(100), nullable=True); state: Mapped[str | None]=mapped_column(String(2), nullable=True); latitude: Mapped[float | None]=mapped_column(Float,nullable=True); longitude: Mapped[float | None]=mapped_column(Float,nullable=True); conditions: Mapped[str | None]=mapped_column(Text,nullable=True); medications: Mapped[str | None]=mapped_column(Text,nullable=True); allergies: Mapped[str | None]=mapped_column(Text,nullable=True); care_needs: Mapped[str | None]=mapped_column(Text,nullable=True); mobility: Mapped[str | None]=mapped_column(Text,nullable=True); session_value: Mapped[Decimal | None]=mapped_column(Numeric(12,2),nullable=True); session_count: Mapped[int | None]=mapped_column(nullable=True); notes: Mapped[str | None]=mapped_column(Text, nullable=True); family_user_id: Mapped[str | None]=mapped_column(ForeignKey("users.id"), nullable=True)
class IntakeRequest(Base, TenantMixin, TimeMixin):
    __tablename__="intake_requests"; id: Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); created_by_id: Mapped[str]=mapped_column(ForeignKey("users.id")); recipient_name: Mapped[str | None]=mapped_column(String(120),nullable=True); recipient_phone: Mapped[str | None]=mapped_column(String(30),nullable=True); token_hash: Mapped[str]=mapped_column(String(64),unique=True,index=True); status: Mapped[str]=mapped_column(String(20),default="pending",index=True); expires_at: Mapped[datetime]=mapped_column(DateTime(timezone=True)); submitted_at: Mapped[datetime | None]=mapped_column(DateTime(timezone=True),nullable=True); patient_id: Mapped[str | None]=mapped_column(ForeignKey("patients.id"),nullable=True); family_data: Mapped[dict | None]=mapped_column(JSON,nullable=True)
class Vehicle(Base, TenantMixin, TimeMixin):
    __tablename__="vehicles"; id: Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); name: Mapped[str]=mapped_column(String(100)); fuel_type: Mapped[str]=mapped_column(String(30),default="gasoline"); average_km_per_liter: Mapped[Decimal]=mapped_column(Numeric(8,2)); fuel_price: Mapped[Decimal]=mapped_column(Numeric(8,2)); additional_cost_per_km: Mapped[Decimal]=mapped_column(Numeric(8,2),default=0); is_default: Mapped[bool]=mapped_column(Boolean,default=False)
class Responsible(Base, TenantMixin, TimeMixin):
    __tablename__="responsibles"; id: Mapped[str]=mapped_column(String(36), primary_key=True, default=uid); patient_id: Mapped[str]=mapped_column(ForeignKey("patients.id")); name: Mapped[str]=mapped_column(String(120)); relationship: Mapped[str]=mapped_column(String(60)); phone: Mapped[str | None]=mapped_column(String(30),nullable=True); email: Mapped[str | None]=mapped_column(String(255),nullable=True); portal_user_id: Mapped[str | None]=mapped_column(ForeignKey("users.id"),nullable=True); patient: Mapped[Patient]=orm_relationship()
class Visit(Base, TenantMixin, TimeMixin):
    __tablename__="visits"; id: Mapped[str]=mapped_column(String(36), primary_key=True, default=uid); patient_id: Mapped[str]=mapped_column(ForeignKey("patients.id")); professional_id: Mapped[str]=mapped_column(ForeignKey("users.id")); starts_at: Mapped[datetime]=mapped_column(DateTime(timezone=True)); duration_minutes: Mapped[int]=mapped_column(default=60); status: Mapped[VisitStatus]=mapped_column(Enum(VisitStatus), default=VisitStatus.SCHEDULED); notes: Mapped[str | None]=mapped_column(Text, nullable=True); confirmation_token_hash: Mapped[str | None]=mapped_column(String(64),nullable=True,unique=True,index=True); confirmation_manual_sent_at: Mapped[datetime | None]=mapped_column(DateTime(timezone=True),nullable=True); confirmation_automatic_sent_at: Mapped[datetime | None]=mapped_column(DateTime(timezone=True),nullable=True); patient_response: Mapped[str | None]=mapped_column(String(20),nullable=True); patient_responded_at: Mapped[datetime | None]=mapped_column(DateTime(timezone=True),nullable=True); patient: Mapped[Patient]=orm_relationship()
class AIAnalysis(Base, TenantMixin, TimeMixin):
    __table_args__=(UniqueConstraint("visit_id","analysis_type",name="uq_ai_visit_type"),)
    __tablename__="ai_analyses"; id: Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); visit_id: Mapped[str]=mapped_column(ForeignKey("visits.id"),index=True); patient_id: Mapped[str]=mapped_column(ForeignKey("patients.id"),index=True); professional_id: Mapped[str]=mapped_column(ForeignKey("users.id"),index=True); analysis_type: Mapped[str]=mapped_column(String(20),index=True); content: Mapped[dict]=mapped_column(JSON); model: Mapped[str]=mapped_column(String(80)); input_tokens: Mapped[int | None]=mapped_column(nullable=True); output_tokens: Mapped[int | None]=mapped_column(nullable=True)
class WhatsAppConfirmation(Base, TenantMixin, TimeMixin):
    __tablename__="whatsapp_confirmations"; id: Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); visit_id: Mapped[str]=mapped_column(ForeignKey("visits.id"),unique=True,index=True); status: Mapped[str]=mapped_column(String(20),default="pending",index=True); attempts: Mapped[int]=mapped_column(default=0); provider_message_id: Mapped[str | None]=mapped_column(String(160),nullable=True); sent_at: Mapped[datetime | None]=mapped_column(DateTime(timezone=True),nullable=True); error_message: Mapped[str | None]=mapped_column(Text,nullable=True)
class ServiceRecord(Base, TenantMixin, TimeMixin):
    __tablename__="service_records"; id: Mapped[str]=mapped_column(String(36), primary_key=True, default=uid); patient_id: Mapped[str]=mapped_column(ForeignKey("patients.id")); visit_id: Mapped[str | None]=mapped_column(ForeignKey("visits.id"), nullable=True); professional_id: Mapped[str]=mapped_column(ForeignKey("users.id")); occurred_at: Mapped[datetime]=mapped_column(DateTime(timezone=True), default=now); summary: Mapped[str]=mapped_column(Text); guidance: Mapped[str | None]=mapped_column(Text, nullable=True); weight_kg: Mapped[Decimal | None]=mapped_column(Numeric(6,2),nullable=True); blood_pressure_systolic: Mapped[int | None]=mapped_column(nullable=True); blood_pressure_diastolic: Mapped[int | None]=mapped_column(nullable=True); heart_rate_bpm: Mapped[int | None]=mapped_column(nullable=True); respiratory_rate_bpm: Mapped[int | None]=mapped_column(nullable=True); temperature_c: Mapped[Decimal | None]=mapped_column(Numeric(4,1),nullable=True); oxygen_saturation_percent: Mapped[int | None]=mapped_column(nullable=True); blood_glucose_mg_dl: Mapped[int | None]=mapped_column(nullable=True); responsible_name: Mapped[str | None]=mapped_column(String(120), nullable=True); signature_data: Mapped[str | None]=mapped_column(Text, nullable=True); professional_signature_name: Mapped[str | None]=mapped_column(String(120),nullable=True); professional_signature_council: Mapped[str | None]=mapped_column(String(100),nullable=True); professional_signature_profession: Mapped[str | None]=mapped_column(String(100),nullable=True); patient: Mapped[Patient]=orm_relationship()
class FinanceEntry(Base, TenantMixin, TimeMixin):
    __tablename__="finance_entries"; id: Mapped[str]=mapped_column(String(36), primary_key=True, default=uid); patient_id: Mapped[str | None]=mapped_column(ForeignKey("patients.id"), nullable=True); entry_type: Mapped[str]=mapped_column(String(20),default="income",index=True); category: Mapped[str]=mapped_column(String(60),default="Outros",index=True); source: Mapped[str | None]=mapped_column(String(40),nullable=True,index=True); description: Mapped[str]=mapped_column(String(160)); amount: Mapped[Decimal]=mapped_column(Numeric(12,2)); due_date: Mapped[date]=mapped_column(Date); paid: Mapped[bool]=mapped_column(Boolean, default=False); patient: Mapped[Patient]=orm_relationship()
class SupportTicket(Base, TenantMixin, TimeMixin):
    __tablename__="support_tickets"
    id: Mapped[str]=mapped_column(String(36),primary_key=True,default=uid)
    ticket_number: Mapped[str]=mapped_column(String(30),unique=True,index=True)
    user_id: Mapped[str]=mapped_column(ForeignKey("users.id"),index=True)
    category: Mapped[str]=mapped_column(String(30),index=True)
    description: Mapped[str]=mapped_column(Text)
    status: Mapped[str]=mapped_column(String(20),default="open",index=True)
    email_sent_at: Mapped[datetime | None]=mapped_column(DateTime(timezone=True),nullable=True)
    admin_response: Mapped[str | None]=mapped_column(Text,nullable=True)
    responded_at: Mapped[datetime | None]=mapped_column(DateTime(timezone=True),nullable=True)
    closed_at: Mapped[datetime | None]=mapped_column(DateTime(timezone=True),nullable=True)
class AuditLog(Base):
    __tablename__="audit_logs"; id: Mapped[str]=mapped_column(String(36), primary_key=True, default=uid); organization_id: Mapped[str]=mapped_column(String(36), index=True); user_id: Mapped[str]=mapped_column(String(36)); action: Mapped[str]=mapped_column(String(80)); resource: Mapped[str]=mapped_column(String(80)); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True), default=now)
class Plan(Base):
    __tablename__="plans"; id: Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); code: Mapped[str]=mapped_column(String(40),unique=True); name: Mapped[str]=mapped_column(String(80)); monthly_price: Mapped[Decimal]=mapped_column(Numeric(12,2)); annual_monthly_price: Mapped[Decimal]=mapped_column(Numeric(12,2)); active: Mapped[bool]=mapped_column(Boolean,default=True); ai_daily_limit: Mapped[int]=mapped_column(default=10); whatsapp_monthly_limit: Mapped[int]=mapped_column(default=0)
class Subscription(Base, TimeMixin):
    __tablename__="subscriptions"; id: Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); organization_id: Mapped[str]=mapped_column(ForeignKey("organizations.id"),unique=True,index=True); plan_id: Mapped[str]=mapped_column(ForeignKey("plans.id")); pending_plan_id: Mapped[str | None]=mapped_column(ForeignKey("plans.id"),nullable=True); status: Mapped[SubscriptionStatus]=mapped_column(Enum(SubscriptionStatus),default=SubscriptionStatus.TRIAL); billing_cycle: Mapped[BillingCycle]=mapped_column(Enum(BillingCycle),default=BillingCycle.MONTHLY); current_period_end: Mapped[date | None]=mapped_column(Date,nullable=True); complimentary_until: Mapped[date | None]=mapped_column(Date,nullable=True); complimentary_note: Mapped[str | None]=mapped_column(String(255),nullable=True); gateway: Mapped[str | None]=mapped_column(String(40),nullable=True); external_id: Mapped[str | None]=mapped_column(String(120),nullable=True); cancel_at_period_end: Mapped[bool]=mapped_column(Boolean,default=False); cancellation_requested_at: Mapped[datetime | None]=mapped_column(DateTime(timezone=True),nullable=True)
class SubscriptionReminder(Base):
    __tablename__="subscription_reminders"
    id: Mapped[str]=mapped_column(String(36),primary_key=True,default=uid)
    subscription_id: Mapped[str]=mapped_column(ForeignKey("subscriptions.id"),index=True)
    reminder_key: Mapped[str]=mapped_column(String(120),unique=True,index=True)
    reminder_type: Mapped[str]=mapped_column(String(30),index=True)
    sent_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class BillingWebhookEvent(Base):
    __tablename__="billing_webhook_events"; id: Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); gateway: Mapped[str]=mapped_column(String(30)); event_id: Mapped[str]=mapped_column(String(160),unique=True,index=True); event_type: Mapped[str]=mapped_column(String(80)); payload: Mapped[dict]=mapped_column(JSON); processed_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class SystemSetting(Base, TimeMixin):
    __tablename__="system_settings"
    id: Mapped[str]=mapped_column(String(36),primary_key=True,default=uid)
    key: Mapped[str]=mapped_column(String(80),unique=True,index=True)
    value: Mapped[dict]=mapped_column(JSON)
    updated_by_id: Mapped[str | None]=mapped_column(String(36),nullable=True)
class ProductEvent(Base):
    __tablename__="product_events"
    id: Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); organization_id: Mapped[str]=mapped_column(String(36),index=True); user_id: Mapped[str]=mapped_column(String(36),index=True); event_name: Mapped[str]=mapped_column(String(80),index=True); source: Mapped[str]=mapped_column(String(40),default="app"); metadata_json: Mapped[dict | None]=mapped_column(JSON,nullable=True); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,index=True)
class CommunicationAutomation(Base, TimeMixin):
    __tablename__="communication_automations"
    id: Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); code: Mapped[str]=mapped_column(String(80),unique=True,index=True); name: Mapped[str]=mapped_column(String(120)); channel: Mapped[str]=mapped_column(String(20),index=True); trigger_type: Mapped[str]=mapped_column(String(50)); offset_days: Mapped[int]=mapped_column(default=0); subject: Mapped[str | None]=mapped_column(String(180),nullable=True); content: Mapped[str]=mapped_column(Text); action_path: Mapped[str | None]=mapped_column(String(180),nullable=True); is_active: Mapped[bool]=mapped_column(Boolean,default=True,index=True); promotional: Mapped[bool]=mapped_column(Boolean,default=False)
class CommunicationLog(Base, TimeMixin):
    __tablename__="communication_logs"
    __table_args__=(UniqueConstraint("idempotency_key",name="uq_communication_idempotency"),)
    id: Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); organization_id: Mapped[str]=mapped_column(String(36),index=True); user_id: Mapped[str]=mapped_column(String(36),index=True); automation_id: Mapped[str | None]=mapped_column(ForeignKey("communication_automations.id"),nullable=True,index=True); channel: Mapped[str]=mapped_column(String(20),index=True); template_code: Mapped[str]=mapped_column(String(80)); idempotency_key: Mapped[str]=mapped_column(String(220)); scheduled_at: Mapped[datetime | None]=mapped_column(DateTime(timezone=True),nullable=True,index=True); attempted_at: Mapped[datetime | None]=mapped_column(DateTime(timezone=True),nullable=True); sent_at: Mapped[datetime | None]=mapped_column(DateTime(timezone=True),nullable=True); status: Mapped[str]=mapped_column(String(30),default="pending",index=True); provider_id: Mapped[str | None]=mapped_column(String(180),nullable=True); attempts: Mapped[int]=mapped_column(default=0); error_message: Mapped[str | None]=mapped_column(Text,nullable=True); skip_reason: Mapped[str | None]=mapped_column(String(255),nullable=True); clicked_at: Mapped[datetime | None]=mapped_column(DateTime(timezone=True),nullable=True); clicked_url: Mapped[str | None]=mapped_column(String(500),nullable=True)
class ContextMessageInteraction(Base, TimeMixin):
    __tablename__="context_message_interactions";__table_args__=(UniqueConstraint("user_id","message_code",name="uq_context_message_user"),)
    id: Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id: Mapped[str]=mapped_column(String(36),index=True);user_id: Mapped[str]=mapped_column(String(36),index=True);message_code: Mapped[str]=mapped_column(String(80),index=True);views: Mapped[int]=mapped_column(default=0);last_viewed_at: Mapped[datetime | None]=mapped_column(DateTime(timezone=True),nullable=True);clicked_at: Mapped[datetime | None]=mapped_column(DateTime(timezone=True),nullable=True);dismissed_at: Mapped[datetime | None]=mapped_column(DateTime(timezone=True),nullable=True)
class ExitSurveyResponse(Base, TimeMixin):
    __tablename__="exit_survey_responses";__table_args__=(UniqueConstraint("user_id","subscription_id",name="uq_exit_survey_cycle"),)
    id: Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id: Mapped[str]=mapped_column(String(36),index=True);user_id: Mapped[str]=mapped_column(String(36),index=True);subscription_id: Mapped[str]=mapped_column(String(36),index=True);reason: Mapped[str]=mapped_column(String(60),index=True);details: Mapped[str | None]=mapped_column(Text,nullable=True)
