import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {Link,useNavigate,useParams} from 'react-router-dom';
import {AlertTriangle,Sparkles} from 'lucide-react';
import {api,post} from './api';
import type {Visit} from './types';
type Analysis={id:string;analysis_type:'preparation'|'evolution';content:{summary:string;attention_points:string[];suggested_questions:string[];next_actions:string[];safety_note:string};model:string;created_at:string};
export default function AIAssistantPage(){const {visitId}=useParams(),navigate=useNavigate(),q=useQueryClient(),{data:visits=[]}=useQuery({queryKey:['visits'],queryFn:()=>api<Visit[]>('/visits')}),{data=[]}=useQuery({queryKey:['visit-ai',visitId],queryFn:()=>api<Analysis[]>(`/visits/${visitId}/ai-analyses`),enabled:!!visitId}),generate=useMutation({mutationFn:(analysis_type:'preparation'|'evolution')=>post<Analysis>(`/visits/${visitId}/ai-analysis`,{analysis_type}),onSuccess:()=>q.invalidateQueries({queryKey:['visit-ai',visitId]})});const get=(type:string)=>data.find(item=>item.analysis_type===type);return <section><div className="mb-7"><h1 className="flex items-center gap-2 text-3xl"><Sparkles className="text-brand"/>Assistente do atendimento</h1><p className="mt-1 text-ink/55">Organize a preparação e a evolução com apoio de IA.</p></div><div className="card mb-6 max-w-2xl"><label><span className="label">Atendimento</span><select className="input" value={visitId||''} onChange={event=>navigate(`/app/visit-assistant/${event.target.value}`)}><option value="">Selecione um atendimento</option>{visits.filter(visit=>visit.status!=='canceled').map(visit=><option key={visit.id} value={visit.id}>{visit.patient.name} — {new Date(visit.starts_at).toLocaleString('pt-BR')}</option>)}</select></label></div>{!visitId?<p className="card text-sm text-ink/55">Selecione um atendimento para usar o assistente.</p>:<><Link className="btn-outline mb-6 inline-flex" to="/app/visits">Voltar à agenda</Link><div className="mb-6 flex gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><AlertTriangle className="shrink-0"/><p>O conteúdo é um rascunho de apoio e deve ser revisado. A IA não realiza diagnóstico, prescrição ou decisão sobre o atendimento.</p></div><div className="grid gap-5 lg:grid-cols-2"><AnalysisCard title="Preparação da próxima visita" item={get('preparation')} action={()=>generate.mutate('preparation')} loading={generate.isPending}/><AnalysisCard title="Síntese da evolução" item={get('evolution')} action={()=>generate.mutate('evolution')} loading={generate.isPending}/></div>{generate.error&&<p className="mt-5 rounded-lg bg-red-50 p-3 text-sm text-red-700">{generate.error.message}</p>}</>}</section>}
function AnalysisCard({title,item,action,loading}:{title:string;item?:Analysis;action:()=>void;loading:boolean}){return <div className="card"><h2 className="text-xl">{title}</h2>{!item?<><p className="mt-2 text-sm text-ink/55">Permitida uma geração por atendimento.</p><button className="btn-primary mt-5 gap-2" onClick={action} disabled={loading}><Sparkles size={17}/>{loading?'Gerando...':'Gerar com IA'}</button></>:<div className="mt-5 space-y-4 text-sm"><p className="leading-6">{item.content.summary}</p><List title="Pontos de atenção" values={item.content.attention_points}/><List title="Perguntas sugeridas" values={item.content.suggested_questions}/><List title="Próximas ações" values={item.content.next_actions}/><p className="rounded-lg bg-sand p-3 text-xs text-ink/60">{item.content.safety_note}</p><p className="text-[11px] text-ink/40">Gerado em {new Date(item.created_at).toLocaleString('pt-BR')}</p></div>}</div>}
function List({title,values}:{title:string;values:string[]}){return <div><b>{title}</b><ul className="mt-2 list-disc space-y-1 pl-5">{values.map(value=><li key={value}>{value}</li>)}</ul></div>}
