import {FormEvent,useEffect,useRef,useState} from 'react';
import {ArrowLeft,HeartHandshake,Mail} from 'lucide-react';
import {useNavigate,useSearchParams} from 'react-router-dom';
import {api,post} from './api';
import {professionCouncil,professions,states} from './formOptions';

const value=(form:FormData,name:string)=>String(form.get(name)||'').trim()||null;
type InputProps={name:string;label:string;type?:string;required?:boolean;minLength?:number;defaultValue?:string;readOnly?:boolean;onBlur?:(event:React.FocusEvent<HTMLInputElement>)=>void};
const Input=({name,label,type='text',required=false,minLength,defaultValue,readOnly,onBlur}:InputProps)=><label className="block"><span className="label">{label}</span><input key={`${name}-${defaultValue||''}`} className={`input ${readOnly?'bg-ink/5':''}`} name={name} type={type} required={required} minLength={minLength} defaultValue={defaultValue} readOnly={readOnly} onBlur={onBlur}/></label>;
type GoogleCredential={credential:string};
type GoogleProfile={name?:string;email?:string};
type TurnstileApi={render:(element:HTMLElement,options:Record<string,unknown>)=>string;reset:(widgetId?:string)=>void;remove:(widgetId:string)=>void};
declare global{interface Window{google?:{accounts:{id:{initialize:(options:{client_id:string;callback:(response:GoogleCredential)=>void})=>void;renderButton:(element:HTMLElement,options:Record<string,unknown>)=>void}}};turnstile?:TurnstileApi}}

function decodeGoogleProfile(credential:string):GoogleProfile{
  try{const part=credential.split('.')[1].replace(/-/g,'+').replace(/_/g,'/');const decoded=decodeURIComponent(Array.from(atob(part),char=>`%${char.charCodeAt(0).toString(16).padStart(2,'0')}`).join(''));return JSON.parse(decoded)}catch{return {}}
}
function GoogleButton({onCredential,signup=false,separated=true}:{onCredential:(credential:string)=>void;signup?:boolean;separated?:boolean}){
  const target=useRef<HTMLDivElement>(null);const clientId=import.meta.env.VITE_GOOGLE_CLIENT_ID;
  useEffect(()=>{if(!clientId||!target.current)return;const render=()=>{if(!window.google||!target.current)return;window.google.accounts.id.initialize({client_id:clientId,callback:r=>onCredential(r.credential)});target.current.innerHTML='';window.google.accounts.id.renderButton(target.current,{theme:'outline',size:'large',width:360,text:signup?'signup_with':'continue_with',locale:'pt-BR'})};const existing=document.querySelector<HTMLScriptElement>('script[data-google-identity]');if(existing){if(window.google)render();else existing.addEventListener('load',render,{once:true});return}const script=document.createElement('script');script.src='https://accounts.google.com/gsi/client';script.async=true;script.dataset.googleIdentity='true';script.onload=render;document.head.appendChild(script)},[clientId,onCredential,signup]);
  if(!clientId)return null;return <>{separated&&<div className="my-5 flex items-center gap-3 text-xs text-ink/40"><span className="h-px flex-1 bg-ink/10"/>ou<span className="h-px flex-1 bg-ink/10"/></div>}<div ref={target} className="flex justify-center"/></>;
}
function Turnstile({onToken,resetKey}:{onToken:(token:string)=>void;resetKey:number}){
  const target=useRef<HTMLDivElement>(null),widgetId=useRef<string>();const siteKey=import.meta.env.VITE_TURNSTILE_SITE_KEY;
  useEffect(()=>{if(!siteKey||!target.current)return;let active=true;const render=()=>{if(!active||!window.turnstile||!target.current||widgetId.current)return;widgetId.current=window.turnstile.render(target.current,{sitekey:siteKey,language:'pt-BR',theme:'light',callback:(token:string)=>onToken(token),'expired-callback':()=>onToken(''),'error-callback':()=>onToken('')})};const existing=document.querySelector<HTMLScriptElement>('script[data-turnstile]');if(existing){if(window.turnstile)render();else existing.addEventListener('load',render,{once:true})}else{const script=document.createElement('script');script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';script.async=true;script.defer=true;script.dataset.turnstile='true';script.onload=render;document.head.appendChild(script)}return()=>{active=false;if(widgetId.current&&window.turnstile){window.turnstile.remove(widgetId.current);widgetId.current=undefined}}},[siteKey,onToken]);
  useEffect(()=>{if(resetKey&&widgetId.current&&window.turnstile){window.turnstile.reset(widgetId.current);onToken('')}},[resetKey,onToken]);
  if(!siteKey)return null;return <div className="pt-1"><div ref={target} className="flex min-h-[65px] justify-center"/><p className="mt-1 text-center text-xs text-ink/45">Verificação de segurança para acesso com senha.</p></div>;
}
function professionalData(form:FormData){return {organization_name:value(form,'organization_name'),phone:value(form,'phone'),cpf:value(form,'cpf'),profession:value(form,'profession'),profession_other:value(form,'profession_other'),council_name:value(form,'council_name'),council_code:value(form,'council_code'),council_state:value(form,'council_state'),postal_code:value(form,'postal_code'),address:value(form,'address'),address_number:value(form,'address_number'),address_complement:value(form,'address_complement'),neighborhood:value(form,'neighborhood'),city:value(form,'city'),state:value(form,'state'),accept_lgpd:form.get('lgpd')==='on'}}
async function findAddress(postalCode:string){const digits=postalCode.replace(/\D/g,'');if(digits.length!==8)return null;const response=await fetch(`https://viacep.com.br/ws/${digits}/json/`);if(!response.ok)throw new Error('Não foi possível consultar o CEP');const data=await response.json();if(data.erro)throw new Error('CEP não encontrado');return {address:data.logradouro||'',neighborhood:data.bairro||'',city:data.localidade||'',state:data.uf||''}}

export function AccountAuth({mode}:{mode:'login'|'register'}){
  const nav=useNavigate();
  const [error,setError]=useState(''),[success,setSuccess]=useState(''),[profession,setProfession]=useState('');
  const [registerMethod,setRegisterMethod]=useState<'email'|'google'|null>(mode==='login'?'email':null);
  const [googleCredential,setGoogleCredential]=useState(''),[googleProfile,setGoogleProfile]=useState<GoogleProfile>({});
  const [captchaToken,setCaptchaToken]=useState(''),[captchaReset,setCaptchaReset]=useState(0);const captchaEnabled=Boolean(import.meta.env.VITE_TURNSTILE_SITE_KEY);
  const [address,setAddress]=useState({address:'',neighborhood:'',city:'',state:''}),[cepStatus,setCepStatus]=useState('');
  const enter=({access_token}:{access_token:string})=>{localStorage.setItem('token',access_token);nav('/app')};
  const google=async(credential:string)=>{setError('');if(mode==='login'){try{enter(await post<{access_token:string}>('/auth/google',{credential}))}catch(reason){setError((reason as Error).message)}return}try{enter(await post<{access_token:string}>('/auth/google',{credential}))}catch(reason){const message=(reason as Error).message;if(!message.includes('Preencha os dados profissionais')){setError(message);return}setGoogleCredential(credential);setGoogleProfile(decodeGoogleProfile(credential));setRegisterMethod('google')}};
  const lookupCep=async(event:React.FocusEvent<HTMLInputElement>)=>{if(!event.target.value.trim())return;setCepStatus('Consultando CEP...');try{const found=await findAddress(event.target.value);if(found){setAddress(found);setCepStatus('Endereço preenchido. Confira os dados.')}}catch(reason){setCepStatus((reason as Error).message)}};
  const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setError('');const form=new FormData(e.currentTarget);try{if(mode==='login'){enter(await post<{access_token:string}>('/auth/login',{email:value(form,'email'),password:value(form,'password'),captcha_token:captchaToken||null}));return}if(registerMethod==='google'){enter(await post<{access_token:string}>('/auth/google',{credential:googleCredential,...professionalData(form)}));return}const data={name:value(form,'name'),email:value(form,'email'),password:value(form,'password'),...professionalData(form)};const result=await post<{message:string}>('/auth/register',data);setSuccess(result.message)}catch(reason){if(mode==='login'&&captchaEnabled)setCaptchaReset(current=>current+1);setError((reason as Error).message)}};
  if(success)return <Page><div className="card w-full max-w-lg !p-8 text-center"><HeartHandshake className="mx-auto text-brand" size={42}/><h1 className="mt-4 text-2xl">Confira seu e-mail</h1><p className="mt-3 text-ink/60">{success}</p><a className="btn-primary mt-6 inline-flex" href="/login">Ir para o login</a></div></Page>;
  if(mode==='register'&&registerMethod===null)return <Page><div className="card w-full max-w-md !p-8"><Brand/><h1 className="text-2xl">Como deseja criar sua conta?</h1><p className="mb-7 mt-2 text-sm text-ink/55">Escolha uma opção para iniciar seu cadastro profissional.</p><GoogleButton onCredential={google} signup separated={false}/><div className="my-5 flex items-center gap-3 text-xs text-ink/40"><span className="h-px flex-1 bg-ink/10"/>ou<span className="h-px flex-1 bg-ink/10"/></div><button className="btn-outline w-full gap-2" onClick={()=>setRegisterMethod('email')}><Mail size={18}/>Cadastrar com e-mail</button>{error&&<p className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<p className="mt-7 text-center text-base">Já possui uma conta? <a className="font-bold text-brand" href="/login">Entrar</a></p></div></Page>;
  return <Page><form onSubmit={submit} className={`card w-full ${mode==='register'?'max-w-3xl':'max-w-md'} !p-8`}><Brand/><h1 className="text-2xl">{mode==='login'?'Bem-vindo de volta':registerMethod==='google'?'Complete seu cadastro profissional':'Crie sua conta profissional'}</h1><p className="mb-6 mt-2 text-sm text-ink/55">{mode==='login'?'Entre na sua conta para continuar.':registerMethod==='google'?'Seu nome e e-mail vieram do Google. Agora informe os dados profissionais.':'30 dias grátis, sem cartão. Confirme seu e-mail para ativar a conta.'}</p>
    {mode==='login'?<div className="space-y-4"><Input name="email" label="E-mail" type="email" required/><div><Input name="password" label="Senha" type="password" required/><a className="mt-2 block text-right text-sm font-semibold text-brand underline" href="/esqueci-senha">Esqueci minha senha</a></div><Turnstile onToken={setCaptchaToken} resetKey={captchaReset}/></div>:<><button type="button" className="mb-5 inline-flex items-center gap-1 text-sm font-semibold text-brand" onClick={()=>{setRegisterMethod(null);setGoogleCredential('');setGoogleProfile({});setError('')}}><ArrowLeft size={16}/>Trocar forma de cadastro</button><div className="grid gap-4 md:grid-cols-2">
      <Input name="name" label="Nome completo" required minLength={3} defaultValue={googleProfile.name} readOnly={registerMethod==='google'}/><Input name="cpf" label="CPF" required/><Input name="phone" label="Telefone/WhatsApp" type="tel" required/><Input name="email" label="E-mail" type="email" required defaultValue={googleProfile.email} readOnly={registerMethod==='google'}/>{registerMethod==='email'&&<Input name="password" label="Senha (mínimo de 8 caracteres)" type="password" required minLength={8}/>}<Input name="organization_name" label="Nome profissional ou do negócio" required/>
      <label className="block"><span className="label">Profissão</span><select className="input" name="profession" required value={profession} onChange={e=>setProfession(e.target.value)}><option value="">Selecione</option>{professions.map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label>
      {profession==='other'&&<Input name="profession_other" label="Informe sua profissão" required/>}
      <label className="block"><span className="label">Conselho profissional</span><input className="input bg-ink/5" name="council_name" value={professionCouncil[profession]||''} placeholder="Não se aplica" readOnly/></label><Input name="council_code" label="Número do conselho (opcional)"/><StateSelect name="council_state" label="UF do conselho (opcional)" optional/>
      <Input name="postal_code" label="CEP (opcional)" onBlur={lookupCep}/><Input name="address" label="Logradouro (opcional)" defaultValue={address.address}/><Input name="address_number" label="Número (opcional)"/><Input name="address_complement" label="Complemento (opcional)"/><Input name="neighborhood" label="Bairro (opcional)" defaultValue={address.neighborhood}/><Input name="city" label="Cidade" required defaultValue={address.city}/><StateSelect name="state" label="Estado (UF)" value={address.state}/>
      {cepStatus&&<p className={`text-sm md:col-span-2 ${cepStatus.includes('preenchido')?'text-brand':'text-amber-700'}`}>{cepStatus}</p>}
      <label className="md:col-span-2 flex items-start gap-2 text-xs text-ink/60"><input className="mt-0.5" name="lgpd" type="checkbox" required/><span>Li e aceito os <a className="font-semibold text-brand underline" href="/termos" target="_blank" rel="noreferrer">Termos de Uso</a> e o <a className="font-semibold text-brand underline" href="/privacidade" target="_blank" rel="noreferrer">Aviso de Privacidade</a>.</span></label>
    </div></>}
    {error&&<p className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button className="btn-primary mt-6 w-full disabled:cursor-not-allowed disabled:opacity-50" disabled={mode==='login'&&captchaEnabled&&!captchaToken}>{mode==='login'?'Entrar':registerMethod==='google'?'Concluir cadastro com Google':'Criar conta e validar e-mail'}</button>{mode==='login'&&<GoogleButton onCredential={google}/>}<div className="mt-7 rounded-xl bg-mint p-4 text-center"><p className="text-base font-semibold">{mode==='login'?'Ainda não possui uma conta?':'Já possui uma conta?'}</p><a className="mt-1 inline-block text-lg font-extrabold text-brand underline" href={mode==='login'?'/cadastro':'/login'}>{mode==='login'?'Criar minha conta':'Entrar agora'}</a></div></form></Page>;
}

export function ConfirmEmail(){const [params]=useSearchParams();const [state,setState]=useState('Validando seu e-mail...'),[ok,setOk]=useState(false);useEffect(()=>{const token=params.get('token');if(!token){setState('Link de confirmação inválido.');return}api<{message:string}>(`/auth/verify-email?token=${encodeURIComponent(token)}`).then(r=>{setOk(true);setState(r.message)}).catch(e=>setState(e.message))},[params]);return <Page><div className="card w-full max-w-lg !p-8 text-center"><HeartHandshake className="mx-auto text-brand" size={42}/><h1 className="mt-4 text-2xl">Confirmação de e-mail</h1><p className={`mt-3 ${ok?'text-brand':'text-ink/60'}`}>{state}</p>{ok&&<a className="btn-primary mt-6 inline-flex" href="/login">Entrar no Impacto Care</a>}</div></Page>}
export function ForgotPassword(){const [message,setMessage]=useState(''),[error,setError]=useState('');return <Page><form className="card w-full max-w-md !p-8" onSubmit={async e=>{e.preventDefault();const email=value(new FormData(e.currentTarget),'email');try{const r=await post<{message:string}>('/auth/forgot-password',{email});setMessage(r.message)}catch(reason){setError((reason as Error).message)}}}><HeartHandshake className="text-brand"/><h1 className="mt-4 text-2xl">Esqueci minha senha</h1><p className="mb-5 mt-2 text-sm text-ink/55">Enviaremos um link válido por uma hora.</p><Input name="email" label="E-mail" type="email" required/>{message&&<p className="mt-4 rounded-lg bg-mint p-3 text-sm">{message}</p>}{error&&<p className="mt-4 text-sm text-red-600">{error}</p>}<button className="btn-primary mt-5 w-full">Enviar link</button><a className="mt-4 block text-center text-sm text-brand" href="/login">Voltar ao login</a></form></Page>}
export function ResetPassword(){const [params]=useSearchParams(),[message,setMessage]=useState(''),[error,setError]=useState('');return <Page><form className="card w-full max-w-md !p-8" onSubmit={async e=>{e.preventDefault();const form=new FormData(e.currentTarget);try{const r=await post<{message:string}>('/auth/reset-password',{token:params.get('token'),password:value(form,'password')});setMessage(r.message)}catch(reason){setError((reason as Error).message)}}}><h1 className="text-2xl">Redefinir senha</h1><div className="mt-5"><Input name="password" label="Nova senha" type="password" required minLength={8}/></div>{message&&<p className="mt-4 rounded-lg bg-mint p-3 text-sm">{message} <a href="/login" className="font-bold">Entrar</a></p>}{error&&<p className="mt-4 text-sm text-red-600">{error}</p>}<button className="btn-primary mt-5 w-full">Salvar nova senha</button></form></Page>}

function Brand(){return <a href="/" className="mb-7 flex items-center gap-2 text-xl font-bold"><HeartHandshake className="text-brand"/>Impacto Care</a>}
function Page({children}:{children:React.ReactNode}){return <div className="grid min-h-screen place-items-center bg-sand px-4 py-10">{children}</div>}
function StateSelect({name,label,optional=false,value}:{name:string;label:string;optional?:boolean;value?:string}){return <label className="block"><span className="label">{label}</span><select key={`${name}-${value||''}`} className="input" name={name} required={!optional} defaultValue={value||''}><option value="">Selecione</option>{states.map(state=><option key={state}>{state}</option>)}</select></label>}
