import {useMutation,useQuery} from '@tanstack/react-query';
import {AlertTriangle,Check,CreditCard,FileText,QrCode,ShieldCheck} from 'lucide-react';
import {api,post} from './api';

type Subscription={status:'trial'|'active'|'past_due'|'canceled';billing_cycle:'monthly'|'annual';current_period_end?:string;gateway?:string;blocked:boolean;phase:'trial'|'active'|'grace'|'blocked';days_remaining?:number;grace_ends_at?:string;plan:{name:string;monthly_price:string;annual_monthly_price:string}};
type PaymentMethod='credit_card'|'pix';

export default function BillingPage(){
  const {data}=useQuery({queryKey:['subscription'],queryFn:()=>api<Subscription>('/billing/subscription')});
  const checkout=useMutation({mutationFn:({cycle,paymentMethod}:{cycle:'monthly'|'annual';paymentMethod:PaymentMethod})=>post<{checkout_url:string}>('/billing/checkout',{billing_cycle:cycle,payment_method:paymentMethod}),onSuccess:r=>location.href=r.checkout_url});
  const request=useMutation({mutationFn:(description:string)=>post<{ticket_number:string}>('/support/tickets',{category:'request',description})});
  const label={trial:'Período gratuito',active:'Assinatura ativa',past_due:'Pagamento pendente',canceled:'Assinatura cancelada'}[data?.status||'trial'];
  return <section>
    <div className="mb-7"><h1 className="flex items-center gap-2 text-3xl"><CreditCard className="text-brand"/>Plano e pagamento</h1><p className="mt-1 text-ink/55">Acompanhe a vigência e gerencie sua assinatura.</p></div>
    {data&&<AccessNotice subscription={data}/>}
    <div className="card mb-6 flex flex-wrap items-center justify-between gap-4"><div><span className="rounded-full bg-mint px-3 py-1 text-xs font-bold text-brand">{label}</span><h2 className="mt-3 text-xl">{data?.plan.name||'Impacto Care'}</h2>{data?.current_period_end&&<p className="text-sm text-ink/55">Vigência atual até {date(data.current_period_end)}</p>}</div><div className="flex items-center gap-2 text-sm text-ink/55"><ShieldCheck className="text-brand"/>Pagamento processado pelo ASAAS</div></div>
    <div className="grid gap-5 lg:grid-cols-2"><Plan title="Mensal" price="R$ 59,90" detail="por mês" action={paymentMethod=>checkout.mutate({cycle:'monthly',paymentMethod})} loading={checkout.isPending}/><Plan title="Anual" price="R$ 39,90" detail="por mês, cobrado R$ 478,80 uma vez ao ano" featured action={paymentMethod=>checkout.mutate({cycle:'annual',paymentMethod})} loading={checkout.isPending}/></div>
    {checkout.error&&<p className="mt-5 rounded-lg bg-red-50 p-3 text-sm text-red-700">{checkout.error.message}</p>}
    <p className="mt-4 rounded-lg bg-blue-50 p-3 text-sm text-blue-800"><b>Pagamento via Pix:</b> o código é gerado no ambiente seguro do ASAAS. Como o Pix não é debitado automaticamente, cada nova vigência dependerá de um novo pagamento.</p>
    <div className="card mt-6"><h2 className="flex items-center gap-2 text-xl"><FileText className="text-brand"/>Regras da assinatura</h2><ul className="mt-4 space-y-3 text-sm leading-6 text-ink/65"><li><b>Teste gratuito:</b> o acesso é bloqueado imediatamente após o fim dos 30 dias.</li><li><b>Plano mensal:</b> existe tolerância de 5 dias depois do término da vigência.</li><li><b>Reativação:</b> ocorre mediante nova contratação de plano.</li><li><b>Cancelamento:</b> pode ser solicitado ao suporte. Reembolso somente quando cabível dentro do prazo legal de 7 dias.</li><li><b>Nota fiscal:</b> emitida quando solicitada pelo cliente.</li><li><b>Lembretes:</b> avisamos em tela e por e-mail sobre a expiração. Os avisos não são cobranças.</li></ul><div className="mt-5 flex flex-wrap gap-3"><button className="btn-outline" disabled={request.isPending} onClick={()=>request.mutate('Solicito o cancelamento da assinatura do Impacto Care. Favor confirmar as condições e a data de encerramento.')}>Solicitar cancelamento</button><button className="btn-outline" disabled={request.isPending} onClick={()=>request.mutate('Solicito a emissão da nota fiscal referente à contratação do Impacto Care. Favor entrar em contato para os dados necessários.')}>Solicitar nota fiscal</button></div>{request.data&&<p className="mt-4 rounded-lg bg-mint p-3 text-sm text-brand">Solicitação registrada no chamado {request.data.ticket_number}.</p>}{request.error&&<p className="mt-4 text-sm text-red-600">{request.error.message}</p>}</div>
    <p className="mt-5 text-center text-xs text-ink/45">Você será direcionado ao ambiente seguro do ASAAS. O Impacto Care não recebe nem armazena os dados completos do cartão.</p>
  </section>
}

function AccessNotice({subscription}:{subscription:Subscription}){if(subscription.phase==='trial'&&subscription.days_remaining!==undefined&&subscription.days_remaining<=7)return <Notice>Seu teste gratuito termina em <b>{Math.max(subscription.days_remaining,0)} dia(s)</b>. Após essa data, o acesso será bloqueado até a contratação de um plano.</Notice>;if(subscription.phase==='grace')return <Notice>Seu plano mensal expirou. Você está no período de tolerância, válido até <b>{date(subscription.grace_ends_at!)}</b>.</Notice>;if(subscription.blocked)return <Notice blocked>Seu acesso está bloqueado porque a vigência terminou. Escolha um plano abaixo para reativar.</Notice>;if(subscription.days_remaining!==undefined&&subscription.days_remaining<=7)return <Notice>Sua vigência termina em <b>{subscription.days_remaining} dia(s)</b>. Este é um lembrete, não uma cobrança.</Notice>;return null}
function Notice({children,blocked=false}:{children:React.ReactNode;blocked?:boolean}){return <div className={`mb-6 flex gap-3 rounded-xl border p-4 text-sm ${blocked?'border-red-200 bg-red-50 text-red-800':'border-amber-200 bg-amber-50 text-amber-900'}`}><AlertTriangle className="shrink-0" size={20}/><p>{children}</p></div>}
function Plan({title,price,detail,featured=false,action,loading}:{title:string;price:string;detail:string;featured?:boolean;action:(paymentMethod:PaymentMethod)=>void;loading:boolean}){return <div className={`card ${featured?'border-2 border-brand':''}`}><div className="flex justify-between"><h2 className="text-xl">{title}</h2>{featured&&<span className="rounded-full bg-brand px-3 py-1 text-xs text-white">Mais econômico</span>}</div><p className="mt-6 text-3xl font-extrabold">{price}</p><p className="text-sm text-ink/50">{detail}</p><ul className="mt-6 space-y-3 text-sm">{['Pacientes e agenda','Registros de atendimento','Portal da família','Financeiro, rotas e avaliações'].map(x=><li className="flex gap-2" key={x}><Check size={17} className="text-brand"/>{x}</li>)}</ul><div className="mt-7 grid gap-3"><button className={featured?'btn-primary w-full':'btn-outline w-full'} onClick={()=>action('credit_card')} disabled={loading}><CreditCard size={18}/>{loading?'Abrindo checkout...':'Pagar com cartão'}</button><button className="btn-outline w-full" onClick={()=>action('pix')} disabled={loading}><QrCode size={18}/>{loading?'Abrindo checkout...':'Pagar com Pix'}</button></div></div>}
function date(value:string){return new Date(value+'T12:00').toLocaleDateString('pt-BR')}
