import {useState} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {AlertTriangle,Check,CreditCard,FileText,QrCode,ShieldCheck} from 'lucide-react';
import {api,post} from './api';

type Subscription={status:'trial'|'active'|'past_due'|'canceled';billing_cycle:'monthly'|'annual';current_period_end?:string;gateway?:string;cancel_at_period_end:boolean;blocked:boolean;phase:'trial'|'active'|'grace'|'blocked';days_remaining?:number;grace_ends_at?:string;ai_used_today:number;licensed_seats:number;plan:{code:string;name:string;monthly_price:string;annual_monthly_price:string;ai_daily_limit:number;whatsapp_monthly_limit:number;per_seat:boolean;minimum_seats:number}};
type CommercialPlan={code:'pro'|'premium'|'company';name:string;monthly_price:string;annual_monthly_price:string;ai_daily_limit:number;whatsapp_monthly_limit:number;per_seat:boolean;minimum_seats:number};
type PaymentMethod='credit_card'|'pix';

export default function BillingPage(){
 const q=useQueryClient(),{data}=useQuery({queryKey:['subscription'],queryFn:()=>api<Subscription>('/billing/subscription')}),{data:plans=[]}=useQuery({queryKey:['billing-plans'],queryFn:()=>api<CommercialPlan[]>('/billing/plans')});
 const checkout=useMutation({mutationFn:(request:{plan_code:string;billing_cycle:string;payment_method:PaymentMethod;seat_count?:number})=>post<{checkout_url:string}>('/billing/checkout',request),onSuccess:result=>location.href=result.checkout_url});
 const cancel=useMutation({mutationFn:()=>post<{message:string}>('/billing/cancel',{}),onSuccess:()=>q.invalidateQueries({queryKey:['subscription']})});
 const request=useMutation({mutationFn:(description:string)=>post<{ticket_number:string}>('/support/tickets',{category:'request',description})});
 const visible=plans.filter(plan=>data?.plan.code==='company'?plan.code==='company':plan.code!=='company');
 return <section><div className="mb-7"><h1 className="flex items-center gap-2 text-3xl"><CreditCard className="text-brand"/>Plano e pagamento</h1><p className="mt-1 text-ink/55">Acompanhe a vigência e gerencie sua assinatura.</p></div>{data&&<AccessNotice subscription={data}/>}<div className="card mb-6 flex flex-wrap items-center justify-between gap-4"><div><span className="rounded-full bg-mint px-3 py-1 text-xs font-bold text-brand">{label(data?.status)}</span><h2 className="mt-3 text-xl">{data?.plan.name||'Impacto Care'}</h2>{data?.current_period_end&&<p className="text-sm text-ink/55">Vigência atual até {date(data.current_period_end)}</p>}{data?.plan.per_seat&&<p className="mt-1 text-sm text-ink/55">{data.licensed_seats} licenças contratadas</p>}</div><div className="flex items-center gap-2 text-sm text-ink/55"><ShieldCheck className="text-brand"/>Pagamento processado pelo ASAAS</div></div><p className="mb-4 text-sm text-ink/55">Uso de IA hoje: <b>{data?.ai_used_today||0}/{data?.plan.ai_daily_limit||5}</b>.</p><div className="grid gap-5 xl:grid-cols-2">{visible.flatMap(plan=>(['monthly','annual'] as const).map(cycle=><Plan key={`${plan.code}-${cycle}`} plan={plan} cycle={cycle} initialSeats={data?.licensed_seats||plan.minimum_seats} loading={checkout.isPending} action={(method,seats)=>checkout.mutate({plan_code:plan.code,billing_cycle:cycle,payment_method:method,seat_count:seats})}/>))}</div>{checkout.error&&<ErrorText error={checkout.error}/>}<p className="mt-4 rounded-lg bg-blue-50 p-3 text-sm text-blue-800"><b>Pagamento via Pix:</b> cada nova vigência depende de um novo pagamento.</p><div className="card mt-6"><h2 className="flex items-center gap-2 text-xl"><FileText className="text-brand"/>Regras da assinatura</h2><ul className="mt-4 space-y-3 text-sm leading-6 text-ink/65"><li>O acesso é bloqueado ao final do teste gratuito.</li><li>O plano mensal possui cinco dias de tolerância.</li><li>Empresas pagam R$ 25,00 por profissional, com mínimo de seis licenças.</li><li>Somente o administrador da empresa gerencia cobrança e financeiro.</li></ul><div className="mt-5 flex flex-wrap gap-3"><button className="btn-outline" disabled={cancel.isPending||data?.cancel_at_period_end||data?.status!=='active'} onClick={()=>confirm('Confirmar cancelamento ao final da vigência?')&&cancel.mutate()}>{data?.cancel_at_period_end?'Cancelamento programado':'Cancelar assinatura'}</button><button className="btn-outline" disabled={request.isPending} onClick={()=>request.mutate('Solicito a emissão da nota fiscal referente à contratação do Impacto Care.')}>Solicitar nota fiscal</button></div>{cancel.data&&<p className="mt-4 rounded-lg bg-mint p-3 text-sm text-brand">{cancel.data.message}</p>}{request.data&&<p className="mt-4 rounded-lg bg-mint p-3 text-sm text-brand">Chamado {request.data.ticket_number} registrado.</p>}</div></section>
}

function Plan({plan,cycle,initialSeats,loading,action}:{plan:CommercialPlan;cycle:'monthly'|'annual';initialSeats:number;loading:boolean;action:(method:PaymentMethod,seats?:number)=>void}){const [seats,setSeats]=useState(Math.max(plan.minimum_seats,initialSeats)),annual=cycle==='annual',unit=Number(annual?plan.annual_monthly_price:plan.monthly_price),monthly=unit*(plan.per_seat?seats:1),annualTotal=monthly*12,premium=plan.code!=='pro';const features=plan.per_seat?[`Mínimo de ${plan.minimum_seats} profissionais`,'Administrador, coordenadores e profissionais','Gestão centralizada da equipe','Licenças adicionais por R$ 25,00']:['Pacientes e agenda','Registros e Portal da família',`IA: até ${plan.ai_daily_limit} ações por dia`,premium?`Até ${plan.whatsapp_monthly_limit} confirmações automáticas/mês`:'Confirmação manual por WhatsApp'];return <div className={`card flex min-h-[410px] flex-col ${premium?'border-brand':''}`}><div className="flex items-start justify-between gap-3"><h2 className="text-xl">{plan.name} · {annual?'Anual':'Mensal'}</h2>{premium&&<span className="rounded-full bg-brand px-3 py-1 text-xs text-white">{plan.per_seat?'Empresarial':'Premium'}</span>}</div><p className="mt-6 text-3xl font-extrabold">R$ {money(monthly)}</p><p className="text-sm text-ink/50">por mês{annual?`, cobrado R$ ${money(annualTotal)} uma vez ao ano`:''}</p>{plan.per_seat&&<label className="mt-4"><span className="label">Quantidade de profissionais</span><input className="input" type="number" min={plan.minimum_seats} max={500} value={seats} onChange={event=>setSeats(Math.max(plan.minimum_seats,Number(event.target.value)||plan.minimum_seats))}/><span className="mt-1 block text-xs text-ink/50">R$ 25,00 por profissional/mês</span></label>}<ul className="mt-5 space-y-3 text-sm">{features.map(feature=><li className="flex gap-2" key={feature}><Check size={17} className="shrink-0 text-brand"/>{feature}</li>)}</ul><div className="mt-auto grid gap-3 pt-7"><button className="btn-primary w-full" disabled={loading} onClick={()=>action('credit_card',plan.per_seat?seats:undefined)}><CreditCard size={18}/>Pagar com cartão</button><button className="btn-outline w-full" disabled={loading} onClick={()=>action('pix',plan.per_seat?seats:undefined)}><QrCode size={18}/>Pagar com Pix</button></div></div>}
function AccessNotice({subscription}:{subscription:Subscription}){if(subscription.phase==='trial'&&subscription.days_remaining!==undefined&&subscription.days_remaining<=7)return <Notice>Seu teste termina em <b>{Math.max(subscription.days_remaining,0)} dia(s)</b>.</Notice>;if(subscription.phase==='grace')return <Notice>Seu plano está no período de tolerância até <b>{date(subscription.grace_ends_at!)}</b>.</Notice>;if(subscription.blocked)return <Notice blocked>Seu acesso está bloqueado. Escolha um plano para reativar.</Notice>;return null}
function Notice({children,blocked=false}:{children:React.ReactNode;blocked?:boolean}){return <div className={`mb-6 flex gap-3 rounded-xl border p-4 text-sm ${blocked?'border-red-200 bg-red-50 text-red-800':'border-amber-200 bg-amber-50 text-amber-900'}`}><AlertTriangle size={20}/><p>{children}</p></div>}
function ErrorText({error}:{error:Error}){return <p className="mt-5 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error.message}</p>}
const label=(status?:string)=>({trial:'Período gratuito',active:'Assinatura ativa',past_due:'Pagamento pendente',canceled:'Assinatura cancelada'}[status||'trial']);const date=(value:string)=>new Date(value+'T12:00').toLocaleDateString('pt-BR');const money=(value:number)=>value.toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});
