import {FormEvent,useState} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {CalendarDays,MessageCircle,Plus,Users} from 'lucide-react';
import {api,post} from './api';
import {states} from './formOptions';
import type {Patient,Visit} from './types';

const val=(form:FormData,name:string)=>String(form.get(name)||'').trim()||null;
const Field=({name,label,type='text',required=false}:{name:string;label:string;type?:string;required?:boolean})=><label className="block"><span className="label">{label}</span><input className="input" name={name} type={type} required={required}/></label>;
const State=()=> <label className="block"><span className="label">Estado (UF)</span><select className="input" name="state"><option value="">Selecione</option>{states.map(x=><option key={x}>{x}</option>)}</select></label>;

export function PatientManagement(){
  const query=useQueryClient(); const {data=[]}=useQuery({queryKey:['patients'],queryFn:()=>api<Patient[]>('/patients')}); const [open,setOpen]=useState(false); const [hasResponsible,setHasResponsible]=useState(false); const [error,setError]=useState('');
  const save=useMutation({mutationFn:(payload:unknown)=>post('/patients',payload),onSuccess:()=>{query.invalidateQueries({queryKey:['patients']});setOpen(false);setHasResponsible(false)},onError:e=>setError(e.message)});
  const submit=(form:FormData)=>save.mutate({name:val(form,'name'),cpf:val(form,'cpf'),birth_date:val(form,'birth_date'),gender:val(form,'gender'),phone:val(form,'phone'),email:val(form,'email'),postal_code:val(form,'postal_code'),address:val(form,'address'),address_number:val(form,'address_number'),address_complement:val(form,'address_complement'),neighborhood:val(form,'neighborhood'),city:val(form,'city'),state:val(form,'state'),notes:val(form,'notes'),responsible:hasResponsible?{name:val(form,'responsible_name'),relationship:val(form,'responsible_relationship'),phone:val(form,'responsible_phone'),email:val(form,'responsible_email')}:null});
  return <section><Header title="Pacientes" subtitle="Cadastro completo e contatos organizados." action={<button className="btn-primary gap-2" onClick={()=>setOpen(true)}><Plus size={18}/>Novo paciente</button>}/><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.map(patient=><div className="card" key={patient.id}><div className="grid h-11 w-11 place-items-center rounded-full bg-mint font-bold text-brand">{patient.name[0]}</div><h3 className="mt-4 text-lg">{patient.name}</h3><p className="mt-1 text-sm text-ink/50">{patient.phone||'Telefone não informado'}</p><p className="mt-2 text-sm">{[patient.address,patient.address_number,patient.city,patient.state].filter(Boolean).join(', ')}</p>{patient.birth_date&&<p className="mt-2 text-xs text-ink/50">Nascimento: {new Date(patient.birth_date+'T12:00').toLocaleDateString('pt-BR')}</p>}</div>)}</div>
    {open&&<Dialog title="Novo paciente" close={()=>setOpen(false)} submit={submit}><div className="grid gap-4 md:grid-cols-2"><Field name="name" label="Nome completo" required/><Field name="cpf" label="CPF (opcional)"/><Field name="birth_date" label="Data de nascimento" type="date"/><label className="block"><span className="label">Gênero (opcional)</span><select className="input" name="gender"><option value="">Selecione</option><option value="female">Feminino</option><option value="male">Masculino</option><option value="other">Outro</option><option value="not_informed">Prefere não informar</option></select></label><Field name="phone" label="Telefone/WhatsApp" type="tel"/><Field name="email" label="E-mail" type="email"/><Field name="postal_code" label="CEP"/><Field name="address" label="Logradouro"/><Field name="address_number" label="Número"/><Field name="address_complement" label="Complemento"/><Field name="neighborhood" label="Bairro"/><Field name="city" label="Cidade"/><State/><Field name="notes" label="Observações"/></div><label className="mt-5 flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={hasResponsible} onChange={e=>setHasResponsible(e.target.checked)}/>Adicionar responsável</label>{hasResponsible&&<div className="mt-4 grid gap-4 rounded-xl bg-mint/50 p-4 md:grid-cols-2"><Field name="responsible_name" label="Nome do responsável" required/><Field name="responsible_relationship" label="Parentesco/vínculo" required/><Field name="responsible_phone" label="Telefone do responsável" type="tel"/><Field name="responsible_email" label="E-mail do responsável" type="email"/></div>}{error&&<p className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}</Dialog>}</section>;
}

export function VisitManagement(){
  const query=useQueryClient(); const {data:patients=[]}=useQuery({queryKey:['patients'],queryFn:()=>api<Patient[]>('/patients')}); const {data:visits=[]}=useQuery({queryKey:['visits'],queryFn:()=>api<Visit[]>('/visits')}); const [open,setOpen]=useState(false);
  const save=useMutation({mutationFn:(payload:unknown)=>post('/visits',payload),onSuccess:()=>{query.invalidateQueries({queryKey:['visits']});setOpen(false)}});
  return <section><Header title="Agenda de visitas" subtitle="Planeje e confirme seus atendimentos." action={<button className="btn-primary" onClick={()=>setOpen(true)}>Agendar visita</button>}/><div className="space-y-3">{visits.map(visit=>{const whatsapp=whatsappUrl(visit);return <div className="card flex flex-wrap items-center gap-5" key={visit.id}><div className="rounded-xl bg-mint p-3 text-center"><b>{new Date(visit.starts_at).getDate()}</b><p className="text-xs uppercase">{new Date(visit.starts_at).toLocaleDateString('pt-BR',{month:'short'})}</p></div><div><h3>{visit.patient.name}</h3><p className="text-sm text-ink/55">{new Date(visit.starts_at).toLocaleString('pt-BR')} • {visit.duration_minutes} min</p></div><div className="ml-auto flex items-center gap-2"><span className="rounded-full bg-mint px-3 py-1 text-xs text-brand">Agendada</span>{whatsapp?<a className="btn-outline gap-2" href={whatsapp} target="_blank" rel="noreferrer"><MessageCircle size={17}/>Confirmar no WhatsApp</a>:<span className="text-xs text-amber-700">Cadastre o WhatsApp do paciente</span>}</div></div>})}</div>
    {open&&<Dialog title="Agendar visita" close={()=>setOpen(false)} submit={form=>save.mutate({patient_id:val(form,'patient_id'),starts_at:new Date(String(form.get('starts_at'))).toISOString(),duration_minutes:Number(form.get('duration_minutes')),notes:val(form,'notes')})}><label className="block"><span className="label">Paciente</span><select className="input" name="patient_id" required><option value="">Selecione</option>{patients.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><div className="mt-4 grid gap-4 md:grid-cols-2"><Field name="starts_at" label="Data e hora" type="datetime-local" required/><label className="block"><span className="label">Duração (minutos)</span><input className="input" name="duration_minutes" type="number" defaultValue="60" min="1" required/></label></div><div className="mt-4"><Field name="notes" label="Observações"/></div></Dialog>}</section>;
}

function whatsappUrl(visit:Visit){const digits=(visit.patient.phone||'').replace(/\D/g,'');if(!digits)return null;const phone=digits.startsWith('55')?digits:`55${digits}`;const date=new Date(visit.starts_at);const message=`Olá, ${visit.patient.name}! Confirmamos sua visita para ${date.toLocaleDateString('pt-BR')} às ${date.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}, com duração prevista de ${visit.duration_minutes} minutos. Por favor, responda a esta mensagem confirmando sua disponibilidade.`;return `https://wa.me/${phone}?text=${encodeURIComponent(message)}`}
function Header({title,subtitle,action}:{title:string;subtitle:string;action:React.ReactNode}){return <div className="mb-7 flex items-end justify-between"><div><h1 className="flex items-center gap-2 text-3xl">{title==='Pacientes'?<Users className="text-brand"/>:<CalendarDays className="text-brand"/>}{title}</h1><p className="mt-1 text-ink/55">{subtitle}</p></div>{action}</div>}
function Dialog({title,close,submit,children}:{title:string;close:()=>void;submit:(form:FormData)=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-50 grid place-items-center bg-ink/40 p-4"><form className="card max-h-[92vh] w-full max-w-3xl overflow-auto !p-7" onSubmit={(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();submit(new FormData(event.currentTarget))}}><div className="mb-5 flex justify-between"><h2 className="text-xl">{title}</h2><button type="button" onClick={close}>✕</button></div>{children}<div className="mt-7 flex justify-end gap-3"><button type="button" className="btn-outline" onClick={close}>Cancelar</button><button className="btn-primary">Salvar</button></div></form></div>}
