import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {Link} from 'react-router-dom';
import {AlertCircle,CalendarCheck2,CheckCheck,ClipboardList,ClockAlert,NotebookTabs,RefreshCw,UserX} from 'lucide-react';
import {api,post} from './api';
type VisitAlert={visit_id:string;patient_id:string;patient_name:string;professional_id:string;professional_name:string;starts_at:string;minutes_late:number};
type HandoffAlert={handoff_id:string;visit_id:string;patient_name:string;professional_name:string;condition_summary:string;pending_items?:string;created_at:string};
type Overview={generated_at:string;delayed_visits:VisitAlert[];absent_professionals:VisitAlert[];unread_handoffs:HandoffAlert[];completed_today:number;pending_records:VisitAlert[];tomorrow:{total:number;uncovered:number;fully_staffed:boolean}};
const when=(value:string)=>new Date(value).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'});
const ClipboardClock=ClipboardList;
export default function CentralOperationsPage(){
 const query=useQueryClient(),overview=useQuery({queryKey:['operational-center'],queryFn:()=>api<Overview>('/company/operations/overview'),refetchInterval:60000});
 const read=useMutation({mutationFn:(id:string)=>post(`/company/operations/handoffs/${id}/read`,{}),onSuccess:()=>query.invalidateQueries({queryKey:['operational-center']})});
 const data=overview.data;if(!data)return <div className="card text-sm text-ink/55">Carregando a situação da operação...</div>;
 const metrics=[{label:'Visitas atrasadas',value:data.delayed_visits.length,Icon:ClockAlert,tone:'red'},{label:'Passagens não lidas',value:data.unread_handoffs.length,Icon:NotebookTabs,tone:'amber'},{label:'Faltas identificadas',value:data.absent_professionals.length,Icon:UserX,tone:'red'},{label:'Visitas concluídas hoje',value:data.completed_today,Icon:CheckCheck,tone:'green'},{label:'Registros pendentes',value:data.pending_records.length,Icon:ClipboardClock,tone:'orange'},{label:'Escalas de amanhã',value:data.tomorrow.fully_staffed?`${data.tomorrow.total} preenchidas`:data.tomorrow.total?`${data.tomorrow.uncovered} sem cobertura`:'Nenhuma',Icon:CalendarCheck2,tone:data.tomorrow.fully_staffed?'green':'amber'}] as const;
 return <section><div className="mb-7 flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl">Central Operacional</h1><p className="mt-1 text-ink/55">Tudo que exige atenção da coordenação, em uma única tela.</p></div><button className="btn-outline" onClick={()=>overview.refetch()} disabled={overview.isFetching}><RefreshCw size={17} className={overview.isFetching?'animate-spin':''}/>Atualizar</button></div>
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{metrics.map(({label,value,Icon,tone})=><article className={`rounded-2xl border bg-white p-5 shadow-sm ${tone==='red'?'border-red-200':tone==='amber'||tone==='orange'?'border-amber-200':'border-emerald-200'}`} key={label}><div className="flex items-center justify-between gap-3"><div><p className="text-sm text-ink/55">{label}</p><b className="mt-2 block text-2xl">{value}</b></div><span className={`grid h-11 w-11 place-items-center rounded-xl ${tone==='red'?'bg-red-50 text-red-600':tone==='amber'||tone==='orange'?'bg-amber-50 text-amber-700':'bg-emerald-50 text-emerald-700'}`}><Icon size={22}/></span></div></article>)}</div>
 <div className="mt-7 grid gap-6 xl:grid-cols-2"><VisitList items={[...data.absent_professionals.map(x=>({...x,kind:'Falta'})),...data.delayed_visits.map(x=>({...x,kind:'Atraso'}))]}/><section className="card"><h2 className="flex items-center gap-2 text-xl"><NotebookTabs className="text-amber-600" size={20}/>Passagens aguardando leitura</h2><div className="mt-4 space-y-3">{data.unread_handoffs.map(item=><article className="rounded-xl border border-ink/10 p-4" key={item.handoff_id}><div className="flex flex-wrap justify-between gap-2"><div><b>{item.patient_name}</b><p className="text-xs text-ink/50">{item.professional_name} · {when(item.created_at)}</p></div><button className="text-sm font-semibold text-brand underline" disabled={read.isPending} onClick={()=>read.mutate(item.handoff_id)}>Marcar como lida</button></div><p className="mt-3 line-clamp-3 text-sm">{item.condition_summary}</p>{item.pending_items&&<p className="mt-2 rounded-lg bg-amber-50 p-2 text-xs"><b>Pendências:</b> {item.pending_items}</p>}</article>)}{!data.unread_handoffs.length&&<Empty text="Todas as passagens foram lidas."/>}</div></section>
 <section className="card xl:col-span-2"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="flex items-center gap-2 text-xl"><ClipboardClock className="text-orange-600" size={20}/>Registros de atendimento pendentes</h2><p className="mt-1 text-sm text-ink/50">Saídas concluídas nos últimos sete dias sem o respectivo registro.</p></div><Link className="btn-outline" to="/app/records">Abrir atendimentos</Link></div><div className="mt-4 grid gap-3 md:grid-cols-2">{data.pending_records.map(item=><article className="rounded-xl border border-ink/10 p-4" key={item.visit_id}><b>{item.patient_name}</b><p className="mt-1 text-sm text-ink/50">{item.professional_name} · {when(item.starts_at)}</p><Link className="mt-3 inline-block text-sm font-semibold text-brand underline" to={`/app/records?visit_id=${item.visit_id}`}>Preencher registro</Link></article>)}{!data.pending_records.length&&<Empty text="Nenhum registro pendente."/>}</div></section></div><p className="mt-5 text-right text-xs text-ink/40">Atualizado em {when(data.generated_at)} · atualização automática a cada minuto</p></section>}
function VisitList({items}:{items:Array<VisitAlert&{kind:string}>}){return <section className="card"><h2 className="flex items-center gap-2 text-xl text-red-700"><AlertCircle size={20}/>Atrasos e faltas</h2><div className="mt-4 space-y-3">{items.map(item=><article className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-red-100 bg-red-50/40 p-4" key={item.visit_id}><div><b>{item.kind}: {item.patient_name}</b><p className="text-sm text-ink/55">{item.professional_name} · {when(item.starts_at)}</p><p className="mt-1 text-xs font-semibold text-red-700">{item.minutes_late} minutos sem entrada</p></div><Link className="text-sm font-semibold text-brand underline" to="/app/operations">Ver escala</Link></article>)}{!items.length&&<Empty text="Nenhum atraso ou falta neste momento."/>}</div></section>}
function Empty({text}:{text:string}){return <div className="rounded-xl bg-emerald-50 p-4 text-sm font-medium text-emerald-800">{text}</div>}
