import {FormEvent,useMemo,useState} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {BriefcaseMedical,CalendarPlus,CheckCircle2,Clock3,LogIn,LogOut,MapPin,NotebookPen} from 'lucide-react';
import {api,post,put} from './api';
import type {Patient,User,Visit} from './types';

type Member={id:string;name:string;role:string;is_active:boolean};
type Attendance={id:string;visit_id:string;professional_id:string;check_in_at:string;check_out_at?:string;location_verified:boolean;check_in_distance_meters?:number;visit:Visit};
type Handoff={id:string;visit_id:string;professional_id:string;condition_summary:string;procedures?:string;medications?:string;occurrences?:string;pending_items?:string;next_shift_guidance?:string;created_at:string;patient:Patient};
const value=(form:FormData,key:string)=>String(form.get(key)||'').trim();
const when=(date:string)=>new Date(date).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'});

export default function EnterpriseOperationsPage({user}:{user:User}){
  const query=useQueryClient(),admin=['company_admin','admin'].includes(user.role),[tab,setTab]=useState<'schedule'|'attendance'|'handoff'>('schedule'),[open,setOpen]=useState(false),[handoffVisit,setHandoffVisit]=useState<Visit>(),[message,setMessage]=useState(''),[error,setError]=useState('');
  const {data:visits=[]}=useQuery({queryKey:['visits'],queryFn:()=>api<Visit[]>('/visits')}),{data:patients=[]}=useQuery({queryKey:['patients'],queryFn:()=>api<Patient[]>('/patients')}),{data:members=[]}=useQuery({queryKey:['company-members'],queryFn:()=>api<Member[]>('/company/members'),enabled:admin}),{data:attendance=[]}=useQuery({queryKey:['enterprise-attendance',admin],queryFn:()=>api<Attendance[]>(admin?'/company/attendance':'/attendance/me')}),{data:handoffs=[]}=useQuery({queryKey:['handoffs'],queryFn:()=>api<Handoff[]>('/handoffs')});
  const memberNames=useMemo(()=>Object.fromEntries(members.map(item=>[item.id,item.name])),[members]),attendanceByVisit=useMemo(()=>Object.fromEntries(attendance.map(item=>[item.visit_id,item])),[attendance]);
  const schedule=useMutation({mutationFn:(body:unknown)=>post('/visits',body),onSuccess:()=>{query.invalidateQueries({queryKey:['visits']});setOpen(false);setMessage('Escala cadastrada com sucesso.')},onError:reason=>setError(reason.message)});
  const punch=useMutation({mutationFn:async({visitId,action}:{visitId:string;action:'check-in'|'check-out'})=>{const position=await locate();return post(`/visits/${visitId}/${action}`,{latitude:position.coords.latitude,longitude:position.coords.longitude,accuracy_meters:position.coords.accuracy})},onSuccess:()=>{query.invalidateQueries({queryKey:['enterprise-attendance']});setMessage('Ponto registrado com sucesso.');setError('')},onError:reason=>setError(reason.message)});
  const saveHandoff=useMutation({mutationFn:({visitId,body}:{visitId:string;body:unknown})=>put(`/visits/${visitId}/handoff`,body),onSuccess:()=>{query.invalidateQueries({queryKey:['handoffs']});setHandoffVisit(undefined);setMessage('Passagem de plantão salva.');setError('')},onError:reason=>setError(reason.message)});
  const upcoming=visits.filter(item=>item.status!=='canceled').sort((a,b)=>+new Date(a.starts_at)-+new Date(b.starts_at));
  return <section><div className="mb-6"><h1 className="flex items-center gap-2 text-3xl"><BriefcaseMedical className="text-brand"/>Operação da empresa</h1><p className="mt-1 text-ink/55">Escalas, ponto e passagem de plantão em um só fluxo.</p></div><div className="mb-6 grid grid-cols-3 gap-2 rounded-2xl bg-white p-2 shadow-sm">{([['schedule','Escalas',CalendarPlus],['attendance','Ponto',Clock3],['handoff','Plantão',NotebookPen]] as const).map(([key,label,Icon])=><button className={`flex min-h-12 items-center justify-center gap-2 rounded-xl px-2 text-sm font-semibold ${tab===key?'bg-brand text-white':'text-ink/60 hover:bg-mint'}`} onClick={()=>setTab(key)} key={key}><Icon size={17}/><span className="hidden sm:inline">{label}</span></button>)}</div>{message&&<p className="mb-4 rounded-xl bg-mint p-4 text-sm text-brand">{message}</p>}{error&&<p className="mb-4 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}
  {tab==='schedule'&&<><div className="mb-4 flex items-center justify-between"><div><h2 className="text-xl">Escalas e atendimentos</h2><p className="text-sm text-ink/50">Cada escala vincula paciente, profissional, data e duração.</p></div>{admin&&<button className="btn-primary" onClick={()=>setOpen(true)}><CalendarPlus size={17}/>Nova escala</button>}</div><div className="space-y-3">{upcoming.map(visit=><article className="card grid gap-3 md:grid-cols-[1.2fr_1fr_auto] md:items-center" key={visit.id}><div><b>{visit.patient.name}</b><p className="text-sm text-ink/50">{when(visit.starts_at)} · {visit.duration_minutes} minutos</p></div><p className="text-sm"><span className="text-ink/45">Profissional</span><br/><b>{memberNames[visit.professional_id]|| (visit.professional_id===user.id?user.name:'Profissional atribuído')}</b></p><span className="rounded-full bg-mint px-3 py-1 text-xs font-semibold text-brand">{visit.patient_response==='confirmed'?'Confirmado':'Programado'}</span></article>)}{!upcoming.length&&<Empty text="Nenhuma escala cadastrada."/>}</div></>}
  {tab==='attendance'&&<><h2 className="text-xl">Registro de entrada e saída</h2><p className="mb-4 text-sm text-ink/50">O celular solicitará sua localização no momento do registro.</p>{admin?<div className="space-y-3">{attendance.map(item=><AttendanceCard item={item} name={memberNames[item.professional_id]}/>) }{!attendance.length&&<Empty text="Nenhum ponto registrado no período."/>}</div>:<div className="space-y-3">{upcoming.map(visit=>{const item=attendanceByVisit[visit.id];return <article className="card" key={visit.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><b>{visit.patient.name}</b><p className="text-sm text-ink/50">{when(visit.starts_at)}</p></div>{!item?<button className="btn-primary" disabled={punch.isPending} onClick={()=>punch.mutate({visitId:visit.id,action:'check-in'})}><LogIn size={17}/>Registrar entrada</button>:!item.check_out_at?<button className="btn-outline" disabled={punch.isPending} onClick={()=>punch.mutate({visitId:visit.id,action:'check-out'})}><LogOut size={17}/>Registrar saída</button>:<span className="flex items-center gap-2 text-sm font-semibold text-brand"><CheckCircle2 size={17}/>Ponto concluído</span>}</div>{item&&<p className="mt-3 text-xs text-ink/55">Entrada: {when(item.check_in_at)}{item.check_out_at?` · Saída: ${when(item.check_out_at)}`:''} · {item.location_verified?'Localização validada':'Local sem coordenadas para validação'}</p>}</article>})}{!upcoming.length&&<Empty text="Você não possui escalas atribuídas."/>}</div>}</>}
  {tab==='handoff'&&<><h2 className="text-xl">Passagem de plantão</h2><p className="mb-4 text-sm text-ink/50">Registre situação, cuidados realizados e pendências para continuidade.</p>{!admin&&<div className="mb-5 flex flex-wrap gap-2">{upcoming.map(visit=><button className="btn-outline" onClick={()=>setHandoffVisit(visit)} key={visit.id}><NotebookPen size={16}/>{visit.patient.name} · {new Date(visit.starts_at).toLocaleDateString('pt-BR')}</button>)}</div>}<div className="space-y-3">{handoffs.map(item=><article className="card" key={item.id}><div className="flex flex-wrap justify-between gap-2"><b>{item.patient.name}</b><time className="text-xs text-ink/45">{when(item.created_at)}</time></div><p className="mt-3 whitespace-pre-wrap text-sm">{item.condition_summary}</p>{item.pending_items&&<p className="mt-3 rounded-xl bg-amber-50 p-3 text-sm"><b>Pendências:</b> {item.pending_items}</p>}<p className="mt-3 text-xs text-ink/45">Profissional: {memberNames[item.professional_id]|| (item.professional_id===user.id?user.name:'Equipe')}</p></article>)}{!handoffs.length&&<Empty text="Nenhuma passagem de plantão registrada."/>}</div></>}
  {open&&<Modal title="Nova escala" close={()=>setOpen(false)} submit={form=>schedule.mutate({patient_id:value(form,'patient_id'),professional_id:value(form,'professional_id'),starts_at:new Date(value(form,'starts_at')).toISOString(),duration_minutes:Number(value(form,'duration_minutes')),notes:value(form,'notes')||null})}><Select label="Paciente" name="patient_id" options={patients.filter(x=>x.status==='active').map(x=>[x.id,x.name])}/><Select label="Profissional" name="professional_id" options={members.filter(x=>x.is_active&&x.role!=='company_admin').map(x=>[x.id,x.name])}/><Field label="Data e hora" name="starts_at" type="datetime-local"/><Field label="Duração (minutos)" name="duration_minutes" type="number" value="60"/><Text label="Orientações da escala" name="notes"/></Modal>}
  {handoffVisit&&<Modal title={`Passagem de plantão — ${handoffVisit.patient.name}`} close={()=>setHandoffVisit(undefined)} submit={form=>saveHandoff.mutate({visitId:handoffVisit.id,body:{condition_summary:value(form,'condition_summary'),procedures:value(form,'procedures')||null,medications:value(form,'medications')||null,occurrences:value(form,'occurrences')||null,pending_items:value(form,'pending_items')||null,next_shift_guidance:value(form,'next_shift_guidance')||null}})}><Text label="Situação do paciente ao final do período" name="condition_summary" required/><Text label="Cuidados e procedimentos realizados" name="procedures"/><Text label="Medicamentos administrados ou observados" name="medications"/><Text label="Ocorrências" name="occurrences"/><Text label="Pendências" name="pending_items"/><Text label="Orientações para o próximo profissional" name="next_shift_guidance"/></Modal>}</section>
}

function locate(){return new Promise<GeolocationPosition>((resolve,reject)=>{if(!navigator.geolocation)return reject(new Error('Este dispositivo não disponibiliza localização.'));navigator.geolocation.getCurrentPosition(resolve,()=>reject(new Error('Permita o acesso à localização para registrar o ponto.')),{enableHighAccuracy:true,timeout:15000,maximumAge:0})})}
function AttendanceCard({item,name}:{item:Attendance;name?:string}){return <article className="card grid gap-3 md:grid-cols-3"><div><b>{item.visit.patient.name}</b><p className="text-sm text-ink/50">{name||'Profissional'}</p></div><p className="text-sm">Entrada: <b>{when(item.check_in_at)}</b><br/>Saída: <b>{item.check_out_at?when(item.check_out_at):'Em atendimento'}</b></p><p className={`flex items-center gap-2 text-sm font-semibold ${item.location_verified?'text-brand':'text-amber-700'}`}><MapPin size={17}/>{item.location_verified?'Localização validada':'Sem coordenadas do paciente'}</p></article>}
function Empty({text}:{text:string}){return <div className="card text-center text-sm text-ink/50">{text}</div>}
function Modal({title,close,submit,children}:{title:string;close:()=>void;submit:(form:FormData)=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-50 grid place-items-center bg-ink/40 p-4"><form className="card max-h-[92vh] w-full max-w-2xl overflow-y-auto !p-7" onSubmit={(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();submit(new FormData(event.currentTarget))}}><div className="mb-5 flex items-center justify-between"><h2 className="text-xl">{title}</h2><button type="button" onClick={close}>×</button></div><div className="grid gap-4 md:grid-cols-2">{children}</div><div className="mt-6 flex justify-end gap-3"><button type="button" className="btn-outline" onClick={close}>Cancelar</button><button className="btn-primary">Salvar</button></div></form></div>}
function Field({label,name,type='text',value}:{label:string;name:string;type?:string;value?:string}){return <label><span className="label">{label}</span><input className="input" name={name} type={type} defaultValue={value} required/></label>}
function Text({label,name,required=false}:{label:string;name:string;required?:boolean}){return <label className="md:col-span-2"><span className="label">{label}</span><textarea className="input min-h-24" name={name} required={required}/></label>}
function Select({label,name,options}:{label:string;name:string;options:string[][]}){return <label><span className="label">{label}</span><select className="input" name={name} required><option value="">Selecione</option>{options.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>}
