import {Link} from 'react-router-dom';
import {ArrowRight,CalendarDays,Check,HeartHandshake,Menu,ShieldCheck,Sparkles,Users} from 'lucide-react';

const benefits=[
  [CalendarDays,'Organização sem complicação','Pacientes, agenda, registros e financeiro reunidos em um só lugar.','bg-emerald-50 text-emerald-700'],
  [Users,'Famílias mais próximas','Compartilhe atualizações e permita confirmações com muito menos retrabalho.','bg-sky-50 text-sky-700'],
  [ShieldCheck,'Rotina com mais confiança','Tenha histórico, permissões e informações importantes sempre organizadas.','bg-amber-50 text-amber-700'],
] as const;

export default function Landing(){return <div className="overflow-hidden bg-[#fbfaf7] text-ink">
  <header className="mx-auto flex max-w-7xl items-center justify-between px-6 py-6">
    <Link to="/" className="flex items-center gap-2 text-xl font-extrabold"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-brand text-white shadow-lg shadow-emerald-900/10"><HeartHandshake size={21}/></span>Impacto Care</Link>
    <nav className="hidden gap-7 text-sm font-semibold md:flex"><a href="#como">Como funciona</a><a href="#beneficios">Benefícios</a><a href="#profissional">Para profissionais</a><a href="#planos">Planos</a><a href="#faq">FAQ</a></nav>
    <div className="hidden gap-3 md:flex"><Link className="btn-outline !py-2" to="/login">Entrar</Link><Link className="btn-primary !py-2" to="/cadastro">Começar agora</Link></div><Menu className="md:hidden"/>
  </header>

  <main>
    <section className="relative mx-auto grid max-w-7xl items-center gap-14 px-6 pb-20 pt-12 lg:grid-cols-[0.92fr_1.08fr] lg:py-24">
      <div className="pointer-events-none absolute -left-40 top-8 h-96 w-96 rounded-full bg-emerald-100/60 blur-3xl"/>
      <div className="relative z-10">
        <span className="inline-flex items-center gap-2 rounded-full border border-emerald-200 bg-white px-4 py-2 text-sm font-bold text-brand shadow-sm"><Sparkles size={16}/>30 dias grátis · Sem cartão</span>
        <h1 className="mt-7 text-5xl font-extrabold leading-[1.06] tracking-tight lg:text-6xl">Mais organização para cuidar com <span className="text-brand">presença.</span></h1>
        <p className="mt-6 max-w-xl text-lg leading-8 text-ink/70">Gerencie pacientes, visitas, registros de atendimento e finanças. Aproxime as famílias e fortaleça sua presença profissional.</p>
        <div className="mt-8 flex flex-wrap gap-3"><Link className="btn-primary gap-2 shadow-lg shadow-emerald-900/10" to="/cadastro">Começar agora <ArrowRight size={18}/></Link><a className="btn-outline" href="mailto:contato@impactocg.com">Solicitar demonstração</a></div>
        <div className="mt-7 flex flex-wrap gap-x-6 gap-y-2 text-sm text-ink/60">{['Sem cartão','Acesso pelo celular','Cancele quando quiser'].map(item=><span className="flex items-center gap-2" key={item}><Check size={16} className="text-brand"/>{item}</span>)}</div>
      </div>
      <div className="relative min-h-[480px]">
        <div className="absolute -inset-4 rotate-2 rounded-[2.2rem] bg-gradient-to-br from-emerald-100 via-sky-50 to-amber-100"/>
        <img className="relative h-[500px] w-full rounded-[2rem] object-cover shadow-2xl shadow-ink/15" src="/images/impacto-care-hero.webp" alt="Profissional de atendimento domiciliar conversando com uma família"/>
        <div className="absolute -bottom-6 left-4 right-4 rounded-2xl border border-white/70 bg-white/95 p-4 shadow-xl backdrop-blur sm:left-auto sm:right-5 sm:w-72">
          <div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-mint text-brand"><CalendarDays/></span><div><b>Rotina organizada</b><p className="text-xs text-ink/55">Agenda, pacientes e família conectados</p></div></div>
          <div className="mt-4 grid grid-cols-3 gap-2 text-center">{[['4','visitas'],['12','pacientes'],['3','confirmadas']].map(([value,label])=><div className="rounded-xl bg-sand p-2" key={label}><b>{value}</b><p className="text-[10px] text-ink/50">{label}</p></div>)}</div>
        </div>
      </div>
    </section>

    <section className="bg-white py-24" id="como"><div className="mx-auto max-w-6xl px-6 text-center"><p className="font-bold tracking-widest text-brand">COMO FUNCIONA</p><h2 className="mx-auto mt-3 max-w-3xl text-4xl">Da primeira conversa ao acompanhamento, tudo conectado</h2><div className="mt-14 grid gap-6 md:grid-cols-3">{[['1','Cadastre e organize','Reúna pacientes e informações importantes.'],['2','Planeje as visitas','Visualize a agenda, horários livres e confirmações.'],['3','Compartilhe o cuidado','Registre atendimentos e aproxime as famílias.']].map((item,index)=><div className="rounded-3xl border border-ink/10 p-8 text-left transition hover:-translate-y-1 hover:shadow-lg" key={item[0]}><span className={`grid h-12 w-12 place-items-center rounded-2xl font-extrabold ${index===0?'bg-emerald-50 text-brand':index===1?'bg-sky-50 text-sky-700':'bg-amber-50 text-amber-700'}`}>{item[0]}</span><h3 className="mt-6 text-xl">{item[1]}</h3><p className="mt-2 leading-7 text-ink/60">{item[2]}</p></div>)}</div></div></section>

    <section className="py-24" id="beneficios"><div className="mx-auto max-w-6xl px-6"><div className="mb-12 max-w-2xl"><p className="font-bold tracking-widest text-brand">FEITO PARA SUA ROTINA</p><h2 className="mt-3 text-4xl">Tecnologia que libera tempo para o que importa</h2></div><div className="grid gap-5 md:grid-cols-3">{benefits.map(([Icon,title,text,color])=><div className="card !rounded-3xl !p-8" key={title}><span className={`grid h-14 w-14 place-items-center rounded-2xl ${color}`}><Icon/></span><h3 className="mt-6 text-xl">{title}</h3><p className="mt-3 leading-7 text-ink/60">{text}</p></div>)}</div></div></section>

    <section className="bg-[#eaf5f1] py-24" id="profissional"><div className="mx-auto grid max-w-6xl items-center gap-12 px-6 lg:grid-cols-2"><div className="relative"><div className="absolute -inset-4 -rotate-2 rounded-[2rem] bg-amber-100"/><img className="relative h-[430px] w-full rounded-[1.75rem] object-cover shadow-xl" src="/images/impacto-care-profissional-negro.webp" alt="Profissional negro de atendimento domiciliar orientando uma família negra"/></div><div><p className="font-bold tracking-widest text-brand">SUA PRESENÇA PROFISSIONAL</p><h2 className="mt-3 text-4xl">Sua experiência inspira confiança antes mesmo do primeiro atendimento</h2><p className="mt-5 text-lg leading-8 text-ink/65">Crie um perfil com foto, formação, especialidades e apresentação profissional. Mostre às famílias como você trabalha e facilite o primeiro contato.</p><ul className="mt-7 space-y-3">{['Perfil estruturado e mais humano','Experiência e especialidades em destaque','Um canal profissional para novas famílias'].map(item=><li className="flex gap-3" key={item}><span className="mt-0.5 grid h-6 w-6 place-items-center rounded-full bg-brand text-white"><Check size={15}/></span>{item}</li>)}</ul><Link className="btn-primary mt-8 inline-flex" to="/cadastro">Criar meu perfil</Link></div></div></section>

    <section className="bg-ink py-24 text-white" id="planos"><div className="mx-auto max-w-6xl px-6 text-center"><p className="font-bold tracking-widest text-emerald-300">PLANOS SIMPLES</p><h2 className="mt-3 text-4xl">Comece gratuitamente e evolua no seu ritmo</h2><p className="mt-3 text-white/65">30 dias grátis, sem cartão, com recursos para organizar sua rotina desde o primeiro dia.</p><div className="mx-auto mt-12 grid gap-5 md:grid-cols-3"><Plan title="Essencial mensal" price="59,90"/><Plan title="Essencial anual" price="39,90"/><Plan title="Premium" price="79,90" highlight premium/></div><p className="mt-5 text-sm text-white/60">Premium anual: equivalente a R$ 59,90/mês, cobrado R$ 718,80 uma vez ao ano.</p></div></section>

    <section className="bg-white py-24" id="faq"><div className="mx-auto max-w-3xl px-6"><h2 className="text-center text-4xl">Perguntas frequentes</h2>{[['Preciso instalar algum programa?','Não. O Impacto Care funciona no navegador, no computador ou celular.'],['Meus dados estão seguros?','Aplicamos controles de acesso, isolamento por conta e boas práticas alinhadas à LGPD.'],['A família vê todas as informações?','Não. Cada familiar visualiza somente as informações compartilhadas dos pacientes vinculados.'],['Como funciona o teste grátis?','Você usa os recursos por 30 dias, sem informar cartão. Ao final, escolha um plano para continuar.'],['Posso cancelar quando quiser?','Sim. O plano mensal não tem fidelidade.']].map(item=><details className="group border-b border-ink/10 py-5" key={item[0]}><summary className="cursor-pointer font-semibold marker:text-brand">{item[0]}</summary><p className="mt-3 leading-7 text-ink/60">{item[1]}</p></details>)}</div></section>
  </main>
  <footer className="bg-sand py-10 text-center text-sm text-ink/50">© 2026 Impacto Care <span className="mx-2">·</span><Link className="hover:text-brand" to="/privacidade">Privacidade</Link><span className="mx-2">·</span><Link className="hover:text-brand" to="/termos">Termos de uso</Link></footer>
</div>}

function Plan({title,price,highlight=false,premium=false}:{title:string;price:string;highlight?:boolean;premium?:boolean}){const items=['30 dias grátis, sem cartão','Pacientes ilimitados','Agenda, registros e portal','Assistente de IA com limites',premium?'100 confirmações automáticas/mês':'Confirmação manual pelo WhatsApp'];return <div className={`rounded-3xl p-8 text-left ${highlight?'bg-brand shadow-2xl shadow-black/20':'border border-white/10 bg-white/[0.07]'}`}>{highlight&&<span className="rounded-full bg-white/20 px-3 py-1 text-xs font-bold">AUTOMAÇÃO</span>}<h3 className="mt-4 text-xl">{title}</h3><p className="mt-3"><b className="text-4xl">R$ {price}</b><span className="text-white/65"> /mês</span></p><ul className="my-7 space-y-3 text-sm">{items.map(item=><li className="flex gap-2" key={item}><Check size={18}/>{item}</li>)}</ul><Link className={`btn w-full ${highlight?'bg-white text-brand':'bg-brand text-white'}`} to="/cadastro">Testar grátis por 30 dias</Link></div>}
