import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {ArrowRight,BarChart3,CalendarDays,Check,ChevronDown,CreditCard,HeartHandshake,LifeBuoy,LockKeyhole,Menu,MessageCircleMore,Route,ShieldCheck,Sparkles,Users,X} from 'lucide-react';

type Cycle='monthly'|'annual';
type EventName='landing_viewed'|'hero_cta_clicked'|'demo_cta_clicked'|'demo_section_viewed'|'video_started'|'video_completed'|'plans_section_viewed'|'plan_selected'|'pricing_cycle_changed'|'faq_opened'|'mobile_sticky_cta_clicked'|'trial_cta_clicked'|'registration_started';
const video={url:'',title:'Veja em menos de 1 minuto',thumbnail:'',alt:'Demonstração rápida da Impacto Care'};
const testimonials:Array<{name:string;profession:string;city:string;quote:string;authorized:boolean;active:boolean}>=[];
const founder:{name?:string;role?:string;presentation?:string;photo?:string}={};
const faq=[
 ['O que é a Impacto Care?','Uma plataforma de gestão para profissionais autônomos de atendimento domiciliar, reunindo pacientes, agenda, registros de atendimento, financeiro, rotas e comunicação.'],
 ['Para quais profissionais a plataforma foi criada?','Para profissionais autônomos que realizam atendimentos domiciliares e precisam organizar sua operação.'],
 ['A Impacto Care é um prontuário eletrônico?','Não. É uma plataforma de gestão com recursos de registro de atendimento e organização administrativa.'],
 ['O teste gratuito exige cartão?','Não. O período gratuito é de 30 dias e não exige cartão.'],
 ['O que acontece quando o teste termina?','O acesso é bloqueado ao final dos 30 dias. Para continuar, é necessário contratar um plano.'],
 ['Posso usar pelo celular?','Sim. A plataforma funciona pelo navegador em computador, tablet ou celular.'],
 ['Como funciona o Portal da Família?','O profissional autoriza o acesso e define quais informações do paciente vinculado podem ser acompanhadas.'],
 ['O familiar vê todos os dados do paciente?','Não. O acesso é restrito ao familiar autorizado e às informações disponibilizadas pelo profissional.'],
 ['Como funciona a confirmação pelo WhatsApp?','O profissional envia um link para confirmar, desmarcar ou solicitar reagendamento. O Premium inclui automações dentro do limite do plano.'],
 ['A IA realiza diagnóstico?','Não. A IA oferece rascunhos de apoio que devem ser revisados. Ela não diagnostica, prescreve ou toma decisões.'],
 ['Como funciona o pagamento anual?','O valor anual é pago antecipadamente e corresponde a um valor mensal equivalente menor.'],
 ['Posso cancelar o plano?','Sim. O acesso permanece até o fim da vigência já paga, conforme as regras apresentadas na plataforma.'],
 ['Meus dados são excluídos após o cancelamento?','A exclusão não é automática. Solicitações relacionadas aos dados devem ser encaminhadas ao suporte.'],
 ['Como funciona o suporte?','O usuário abre um chamado na própria plataforma e acompanha a resposta pelo número gerado.'],
] as const;

function track(event:EventName,metadata:Record<string,unknown>={}){const item={event,metadata:{...metadata,device:innerWidth<768?'mobile':innerWidth<1100?'tablet':'desktop'},timestamp:new Date().toISOString()};dispatchEvent(new CustomEvent('impacto:analytics',{detail:item}));const items=JSON.parse(sessionStorage.getItem('impacto_landing_events')||'[]');sessionStorage.setItem('impacto_landing_events',JSON.stringify([...items.slice(-49),item]))}
function attribution(){const query=new URLSearchParams(location.search),keys=['utm_source','utm_medium','utm_campaign','utm_content','utm_term'];if(!localStorage.getItem('impacto_attribution'))localStorage.setItem('impacto_attribution',JSON.stringify({...Object.fromEntries(keys.flatMap(k=>query.get(k)?[[k,query.get(k)]]:[])),landing_page:location.href,referrer:document.referrer,first_visit_at:new Date().toISOString()}))}
function signup(plan?:string,cycle?:Cycle){const saved=JSON.parse(localStorage.getItem('impacto_attribution')||'{}'),current=new URLSearchParams(location.search),p=new URLSearchParams();['utm_source','utm_medium','utm_campaign','utm_content','utm_term'].forEach(k=>{const value=current.get(k)||saved[k];if(value)p.set(k,value)});if(plan)p.set('plan',plan);if(cycle)p.set('cycle',cycle);return `/cadastro${p.size?`?${p}`:''}`}

export default function LandingConversion(){const [menu,setMenu]=useState(false),[sticky,setSticky]=useState(false),[final,setFinal]=useState(false);useEffect(()=>{attribution();track('landing_viewed');const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.target.id==='hero')setSticky(!e.isIntersecting);if(e.target.id==='final-cta')setFinal(e.isIntersecting);if(e.isIntersecting&&e.target.id==='demonstracao')track('demo_section_viewed');if(e.isIntersecting&&e.target.id==='planos')track('plans_section_viewed')}),{threshold:.2});['hero','demonstracao','planos','final-cta'].forEach(id=>{const el=document.getElementById(id);if(el)io.observe(el)});return()=>io.disconnect()},[]);return <div className="overflow-hidden bg-[#fbfaf7] pb-20 text-ink md:pb-0">
 <Header open={menu} setOpen={setMenu}/><main>
 <section id="hero" className="relative mx-auto grid max-w-7xl scroll-mt-24 items-center gap-14 px-6 pb-20 pt-12 lg:grid-cols-2 lg:py-24"><div className="relative z-10"><Badge>Mais organização para cuidar com presença.</Badge><h1 className="mt-7 text-4xl font-extrabold leading-[1.07] sm:text-5xl lg:text-6xl">Organize pacientes, agenda e atendimentos domiciliares em um só lugar</h1><p className="mt-6 max-w-xl text-lg leading-8 text-ink/70">Uma plataforma de gestão para profissionais autônomos que querem reduzir tarefas administrativas, organizar a rotina e melhorar a comunicação com as famílias.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Trial source="hero" event="hero_cta_clicked"/><a className="btn-outline" href="#demonstracao" onClick={()=>track('demo_cta_clicked',{source:'hero'})}>Assistir demonstração</a></div><Checks items={['30 dias gratuitos','Sem cartão','Configuração simples','Cancele quando quiser']}/></div><div className="relative min-h-[390px] sm:min-h-[480px]"><div className="absolute -inset-3 rotate-2 rounded-[2rem] bg-gradient-to-br from-emerald-100 via-sky-50 to-amber-100"/><img width="1536" height="1024" fetchPriority="high" className="relative h-[390px] w-full rounded-[1.75rem] object-cover shadow-2xl sm:h-[500px]" src="/images/impacto-care-hero.webp" alt="Profissional de atendimento domiciliar conversando com uma família"/><div className="absolute -bottom-5 left-3 right-3 rounded-2xl bg-white/95 p-4 shadow-xl sm:left-auto sm:right-5 sm:w-72"><b className="flex items-center gap-2"><CalendarDays className="text-brand"/>Rotina organizada</b><p className="mt-1 text-xs text-ink/55">Agenda, pacientes e família conectados</p></div></div></section>
 <How/><Demo/><Problems/><Benefits/><AIAssistantHighlight/><Presence/><Trust/><Objections/>{testimonials.some(x=>x.active&&x.authorized)&&<Social/>}{founder.name&&founder.presentation&&<Founder/>}<Pricing/><Enterprise/><Faq/><Final/>
 </main><footer className="bg-sand py-10 text-center text-sm text-ink/50">© 2026 Impacto Care · <Link to="/privacidade">Privacidade</Link> · <Link to="/termos">Termos de uso</Link></footer>{sticky&&!final&&<div className="fixed inset-x-0 bottom-0 z-40 border-t bg-white/95 p-3 pb-[calc(.75rem+env(safe-area-inset-bottom))] md:hidden"><Link className="btn-primary w-full" to={signup()} onClick={()=>{track('mobile_sticky_cta_clicked');track('trial_cta_clicked',{source:'sticky'});track('registration_started',{source:'sticky'})}}>Testar grátis por 30 dias</Link></div>}</div>}

function Header({open,setOpen}:{open:boolean;setOpen:(x:boolean)=>void}){const links=[['Como funciona','#como'],['Demonstração','#demonstracao'],['Benefícios','#beneficios'],['Planos','#planos'],['FAQ','#faq']];return <header className="sticky top-0 z-50 border-b border-ink/5 bg-[#fbfaf7]/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4"><Link to="/" className="flex items-center gap-2 text-xl font-extrabold"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-brand text-white"><HeartHandshake/></span>Impacto Care</Link><nav className="hidden gap-6 text-sm font-semibold lg:flex">{links.map(x=><a href={x[1]} key={x[1]}>{x[0]}</a>)}</nav><div className="hidden gap-3 md:flex"><Link className="btn-outline !py-2" to="/login">Entrar</Link><Link className="btn-primary !py-2" to={signup()} onClick={()=>track('registration_started',{source:'header'})}>Começar agora</Link></div><button className="grid h-11 w-11 place-items-center rounded-xl border md:hidden" aria-label={open?'Fechar menu':'Abrir menu'} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div>{open&&<nav className="border-t bg-white p-5 md:hidden">{links.map(x=><a className="block p-3 font-semibold" href={x[1]} key={x[1]} onClick={()=>setOpen(false)}>{x[0]}</a>)}<Link className="btn-primary mt-3 w-full" to={signup()}>Começar agora</Link></nav>}</header>}
function How(){return <Section id="como" white eyebrow="COMO FUNCIONA" title="Da primeira conversa ao acompanhamento, tudo conectado"><div className="grid gap-6 md:grid-cols-3">{[['1','Cadastre e organize','Reúna pacientes e informações importantes.'],['2','Planeje as visitas','Visualize agenda, horários livres e confirmações.'],['3','Compartilhe o cuidado','Registre atendimentos e aproxime as famílias.']].map(x=><Card key={x[0]}><b className="grid h-12 w-12 place-items-center rounded-2xl bg-mint text-brand">{x[0]}</b><h3 className="mt-5 text-xl">{x[1]}</h3><p className="mt-2 text-ink/60">{x[2]}</p></Card>)}</div></Section>}
function Demo(){const rows=[['/images/landing-agenda.webp','Tela da agenda mensal da Impacto Care','Organize sua agenda','Visualize atendimentos, horários disponíveis, confirmações e reagendamentos em um só calendário.'],['/images/landing-atendimentos.webp','Tela de consulta dos registros de atendimento','Centralize os registros de atendimento','Consulte o histórico por paciente, registre orientações e gere PDFs para usuários autorizados.'],['/images/landing-financeiro.webp','Visão geral financeira com receitas, despesas e projeções','Acompanhe sua operação','Controle receitas, despesas, valores pendentes e projeções dos próximos períodos.']] as const;return <Section id="demonstracao" eyebrow="DEMONSTRAÇÃO" title="Veja a Impacto Care funcionando" intro="Conheça como a plataforma conecta agenda, pacientes, registros de atendimento e gestão financeira."><div className="space-y-16">{rows.map(([src,alt,title,text],i)=><article className="grid items-center gap-8 lg:grid-cols-2" key={title}><div className={`overflow-hidden rounded-3xl border border-ink/10 bg-white p-2 shadow-xl shadow-ink/10 ${i%2?'lg:order-last':''}`}><img width="1800" height="1200" loading="lazy" className="h-auto w-full rounded-2xl" src={src} alt={alt}/></div><div><span className="text-sm font-bold text-brand">0{i+1}</span><h3 className="mt-2 text-3xl">{title}</h3><p className="mt-4 text-lg leading-8 text-ink/60">{text}</p></div></article>)}</div>{video.url&&<video controls className="mt-14 w-full rounded-3xl" poster={video.thumbnail} aria-label={video.alt} onPlay={()=>track('video_started')} onEnded={()=>track('video_completed')}><source src={video.url}/></video>}</Section>}
function Problems(){const xs=[[CalendarDays,'Agenda do celular para organizar visitas'],[MessageCircleMore,'WhatsApp para confirmar atendimentos'],[Users,'Papel ou planilha para controlar pacientes'],[HeartHandshake,'Conversas espalhadas para atualizar familiares'],[CreditCard,'Anotações separadas para receitas e despesas'],[Route,'Dificuldade para calcular custos de deslocamento']] as const;return <Section white title="Sua rotina ainda depende de várias ferramentas separadas?" intro="É comum começar dessa forma. Centralizar as atividades ajuda a enxergar melhor o dia a dia."><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{xs.map(([I,t])=><div className="flex gap-4 rounded-2xl border p-5" key={t}><I className="shrink-0 text-brand"/><span>{t}</span></div>)}</div><p className="mt-10 rounded-2xl bg-mint p-6 text-center text-lg font-semibold">A Impacto Care reúne essas atividades em uma única plataforma de gestão.</p></Section>}
function Benefits(){const xs=[['Menos tarefas repetitivas','Centralize pacientes, agenda, registros e informações administrativas para reduzir retrabalho.'],['Mais clareza na rotina','Visualize próximos atendimentos, horários disponíveis e pendências em um único ambiente.'],['Comunicação mais organizada','Compartilhe registros autorizados e facilite o acompanhamento pelos familiares.'],['Mais controle da operação','Acompanhe receitas, despesas, deslocamentos e custos relacionados aos atendimentos.']];return <Section id="beneficios" eyebrow="BENEFÍCIOS" title="Tecnologia para organizar a parte administrativa"><div className="grid gap-5 md:grid-cols-2">{xs.map((x,i)=><Card key={x[0]}><b className="grid h-12 w-12 place-items-center rounded-2xl bg-sky-50 text-sky-700">{i+1}</b><h3 className="mt-5 text-xl">{x[0]}</h3><p className="mt-3 leading-7 text-ink/60">{x[1]}</p></Card>)}</div></Section>}
function AIAssistantHighlight(){return <section className="relative overflow-hidden bg-ink py-24 text-white"><div className="absolute -right-24 -top-24 h-80 w-80 rounded-full bg-brand/30 blur-3xl"/><div className="relative mx-auto grid max-w-6xl items-center gap-12 px-6 lg:grid-cols-[1fr_.85fr]"><div><span className="inline-flex items-center gap-2 rounded-full bg-emerald-300/15 px-4 py-2 text-sm font-bold text-emerald-200"><Sparkles size={17}/>ASSISTENTE DE IA</span><h2 className="mt-6 text-4xl">Prepare o próximo atendimento com mais contexto</h2><p className="mt-5 max-w-2xl text-lg leading-8 text-white/70">O Assistente de IA utiliza as informações já registradas para ajudar a organizar um resumo, pontos de atenção, perguntas sugeridas e próximas ações para revisão do profissional.</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{['Preparação para a próxima visita','Síntese da evolução registrada','Perguntas sugeridas para revisão','Uso controlado conforme o plano'].map(item=><span className="flex gap-3 rounded-xl bg-white/[.07] p-4" key={item}><Check className="shrink-0 text-emerald-300"/>{item}</span>)}</div><p className="mt-6 rounded-xl border border-amber-200/20 bg-amber-100/10 p-4 text-sm text-amber-100">O conteúdo é um rascunho de apoio e deve ser revisado. A IA não realiza diagnóstico, prescrição ou decisão sobre o atendimento.</p></div><div className="rounded-3xl border border-white/10 bg-white/[.07] p-6 shadow-2xl"><div className="flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-brand"><Sparkles/></span><div><b>Preparação da próxima visita</b><p className="text-sm text-white/50">Apoio baseado no histórico disponível</p></div></div><div className="mt-6 space-y-3"><div className="h-3 w-full rounded bg-white/10"/><div className="h-3 w-5/6 rounded bg-white/10"/><div className="h-3 w-3/4 rounded bg-white/10"/></div><div className="mt-6 rounded-2xl bg-white/[.06] p-4"><b className="text-sm text-emerald-200">Pontos para revisar</b><ul className="mt-3 space-y-2 text-sm text-white/60"><li>• Evolução informada anteriormente</li><li>• Orientações registradas</li><li>• Necessidades para a próxima visita</li></ul></div></div></div></section>}
function Presence(){return <section className="bg-[#eaf5f1] py-24"><div className="mx-auto grid max-w-6xl items-center gap-12 px-6 lg:grid-cols-2"><img width="1536" height="1024" loading="lazy" className="h-[340px] w-full rounded-3xl object-cover shadow-xl sm:h-[430px]" src="/images/impacto-care-profissional-negro.webp" alt="Profissional negro de atendimento domiciliar orientando uma família negra"/><div><Badge>SUA PRESENÇA PROFISSIONAL</Badge><h2 className="mt-5 text-4xl">Sua experiência inspira confiança antes do primeiro atendimento</h2><p className="mt-5 text-lg leading-8 text-ink/65">Crie um perfil com foto, formação, especialidades e apresentação profissional para facilitar o primeiro contato.</p><Link className="btn-primary mt-8" to={signup()}>Criar meu perfil</Link></div></div></section>}
function Trust(){const xs=[[ShieldCheck,'Plataforma brasileira','Comunicação e operação adaptadas à realidade brasileira.'],[Users,'Dados organizados por conta','Informações separadas e acessadas conforme permissões.'],[LockKeyhole,'Acesso protegido','Login protegido e confirmação de e-mail.'],[HeartHandshake,'Respeito à privacidade','Princípios de privacidade e proteção de dados.'],[CreditCard,'Pagamento por ASAAS','Cobranças processadas por integração com o ASAAS.'],[LifeBuoy,'Suporte em português','Chamados e respostas diretamente pela plataforma.']] as const;return <Section white title="Uma plataforma pensada para profissionais brasileiros"><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{xs.map(([I,t,d])=><Card key={t}><I className="text-brand"/><h3 className="mt-4 text-lg">{t}</h3><p className="mt-2 text-ink/60">{d}</p></Card>)}</div></Section>}
function Objections(){const xs=[['Tenho poucos pacientes. Vale a pena?','Comece pelo teste gratuito e use os recursos adequados à sua rotina.'],['Não tenho facilidade com tecnologia.','A plataforma foi desenvolvida para uso simples e orientação inicial.'],['Já uso WhatsApp e agenda do celular.','A Impacto Care conecta pacientes, atendimentos, registros, financeiro, rotas e comunicação.'],['Preciso cadastrar cartão para testar?','Não. O período gratuito é de 30 dias e não exige cartão.']];return <Section title="Feita para organizar a rotina sem complicação"><div className="grid gap-4 md:grid-cols-2">{xs.map(x=><Card key={x[0]}><h3 className="text-lg">{x[0]}</h3><p className="mt-3 text-ink/60">{x[1]}</p></Card>)}</div></Section>}
function Pricing(){const plans=[{code:'pro',cycle:'monthly' as Cycle,title:'Essencial mensal',price:'R$ 59,90',suffix:'por mês',text:'Para organizar pacientes, agenda, registros, financeiro e comunicação.'},{code:'pro',cycle:'annual' as Cycle,title:'Essencial anual',price:'R$ 39,90',suffix:'por mês no plano anual',annual:'Cobrança anual antecipada de R$ 478,80',saving:'Economize R$ 240 por ano.',text:'A mesma estrutura do Essencial mensal com menor valor mensal equivalente.'},{code:'premium',cycle:'monthly' as Cycle,title:'Premium mensal',price:'R$ 79,90',suffix:'por mês',text:'Para automatizar confirmações e ampliar o uso da IA.',premium:true},{code:'premium',cycle:'annual' as Cycle,title:'Premium anual',price:'R$ 59,90',suffix:'por mês no plano anual',annual:'Cobrança anual antecipada de R$ 718,80',saving:'Economize R$ 240 por ano.',text:'Mais automação com menor valor mensal equivalente.',premium:true}];return <section id="planos" className="scroll-mt-24 bg-ink py-24 text-white"><div className="mx-auto max-w-7xl px-6 text-center"><h2 className="text-4xl">Todos os planos e valores</h2><p className="mx-auto mt-4 max-w-2xl text-white/65">Compare mensal e anual sem alternar telas. Nos planos anuais, o valor destacado é o equivalente por mês e a cobrança total ocorre uma vez ao ano.</p><div className="mt-10 grid gap-5 md:grid-cols-2 xl:grid-cols-4">{plans.map(plan=><article className={`flex rounded-3xl p-7 text-left ${plan.premium?'bg-brand':'border border-white/10 bg-white/[.07]'}`} key={`${plan.code}-${plan.cycle}`}><div className="flex w-full flex-col">{plan.premium&&<span className="w-fit rounded-full bg-white/20 px-3 py-1 text-xs font-bold">MAIS AUTOMAÇÃO</span>}<h3 className="mt-4 text-xl">{plan.title}</h3><b className="mt-4 block text-4xl">{plan.price}</b><p className="mt-1 font-semibold text-emerald-200">{plan.suffix}</p>{plan.annual&&<div className="mt-4 rounded-xl bg-white/10 p-3"><b className="block text-sm">{plan.annual}</b><span className="mt-1 block text-xs text-white/65">{plan.saving}</span></div>}<p className="mt-5 leading-7 text-white/70">{plan.text}</p><ul className="my-7 space-y-3 text-sm"><li>✓ Pacientes, agenda e registros</li><li>✓ Financeiro, rotas e Portal da Família</li><li>✓ {plan.premium?'Até 100 confirmações automáticas/mês':'Confirmação manual pelo WhatsApp'}</li><li>✓ Assistente de IA com limites do plano</li></ul><Link className={`btn mt-auto w-full ${plan.premium?'bg-white text-brand':'bg-brand text-white'}`} to={signup(plan.code,plan.cycle)} onClick={()=>{track('plan_selected',{plan:plan.code,cycle:plan.cycle});track('registration_started',{source:'pricing',plan:plan.code,cycle:plan.cycle})}}>Testar grátis por 30 dias</Link></div></article>)}</div></div></section>}
function Enterprise(){return <section className="bg-emerald-50 py-20"><div className="mx-auto grid max-w-6xl items-center gap-10 px-6 lg:grid-cols-2"><div><span className="rounded-full bg-brand px-3 py-1 text-xs font-bold text-white">PARA PEQUENAS EMPRESAS</span><h2 className="mt-5 text-4xl">Gestão centralizada da equipe de atendimento domiciliar</h2><p className="mt-4 text-lg leading-8 text-ink/65">Cadastre administradores, coordenadores e profissionais, organize pacientes e controle as licenças em uma única conta empresarial.</p></div><div className="card !p-8"><p className="text-sm text-ink/50">Impacto Care Empresarial</p><b className="mt-2 block text-4xl">R$ 25,00</b><p className="text-ink/55">por profissional/mês · mínimo de 6 profissionais</p><ul className="my-6 space-y-3 text-sm"><li>✓ Administração centralizada</li><li>✓ Convites e controle de acessos</li><li>✓ Pacientes e agenda compartilhados</li><li>✓ Licenças adicionais a partir do 7º profissional</li></ul><Link className="btn-primary w-full" to="/cadastro-empresa">Cadastrar minha empresa</Link></div></div></section>}
function Faq(){return <Section id="faq" white title="Perguntas frequentes"><div className="mx-auto max-w-3xl">{faq.map(([q,a])=><details className="group border-b py-5" key={q} onToggle={e=>e.currentTarget.open&&track('faq_opened',{question:q})}><summary className="flex cursor-pointer list-none justify-between gap-4 font-semibold focus-visible:outline focus-visible:outline-2 focus-visible:outline-brand">{q}<ChevronDown className="shrink-0 group-open:rotate-180"/></summary><p className="mt-3 pr-8 leading-7 text-ink/60">{a}</p></details>)}</div></Section>}
function Final(){return <section id="final-cta" className="bg-gradient-to-br from-emerald-100 via-white to-sky-100 py-24"><div className="mx-auto max-w-4xl px-6 text-center"><h2 className="text-4xl">Comece a organizar sua rotina de atendimento domiciliar</h2><p className="mx-auto mt-5 max-w-2xl text-lg text-ink/65">Teste a Impacto Care gratuitamente por 30 dias, sem cartão, e conheça os recursos no seu ritmo.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Trial source="final"/><a className="btn-outline" href="#planos">Conhecer os planos</a></div><Checks items={['30 dias gratuitos','Sem cartão','Computador, tablet ou celular']}/></div></section>}
function Social(){return <Section title="O que os profissionais estão dizendo"><div className="grid gap-5 md:grid-cols-3">{testimonials.filter(x=>x.active&&x.authorized).slice(0,6).map(x=><blockquote className="card" key={x.name}>“{x.quote}”<footer className="mt-4"><b>{x.name}</b><p>{x.profession} · {x.city}</p></footer></blockquote>)}</div></Section>}
function Founder(){return <Section white title="Por que criamos a Impacto Care" intro={founder.presentation}><p className="font-semibold">{founder.name} · {founder.role}</p></Section>}
function Section({id,white=false,eyebrow,title,intro,children}:{id?:string;white?:boolean;eyebrow?:string;title:string;intro?:string;children:React.ReactNode}){return <section id={id} className={`scroll-mt-24 py-24 ${white?'bg-white':''}`}><div className="mx-auto max-w-6xl px-6">{eyebrow&&<p className="font-bold tracking-widest text-brand">{eyebrow}</p>}<h2 className="max-w-3xl text-4xl">{title}</h2>{intro&&<p className="mt-4 max-w-3xl text-lg leading-8 text-ink/60">{intro}</p>}<div className="mt-12">{children}</div></div></section>}
function Card({children}:{children:React.ReactNode}){return <div className="rounded-3xl border border-ink/10 bg-white p-7 shadow-sm">{children}</div>}
function Badge({children}:{children:React.ReactNode}){return <span className="inline-flex items-center gap-2 rounded-full border border-emerald-200 bg-white px-4 py-2 text-sm font-bold text-brand"><Sparkles size={16}/>{children}</span>}
function Checks({items}:{items:string[]}){return <div className="mt-7 flex flex-wrap justify-center gap-x-5 gap-y-2 text-sm text-ink/60">{items.map(x=><span className="flex gap-2" key={x}><Check className="text-brand" size={16}/>{x}</span>)}</div>}
function Trial({source,event='trial_cta_clicked'}:{source:string;event?:EventName}){return <Link className="btn-primary gap-2" to={signup()} onClick={()=>{track(event,{source});if(event!=='trial_cta_clicked')track('trial_cta_clicked',{source});track('registration_started',{source})}}>Começar teste gratuito <ArrowRight size={18}/></Link>}
