import {HeartHandshake} from 'lucide-react';
import {Link} from 'react-router-dom';

const updated='16 de julho de 2026';
const contact='contato@impactocg.com';
function LegalPage({title,intro,children}:{title:string;intro:string;children:React.ReactNode}){return <div className="min-h-screen bg-sand text-ink"><header className="border-b border-ink/10 bg-white"><div className="mx-auto flex max-w-5xl items-center justify-between px-6 py-5"><Link to="/" className="flex items-center gap-2 text-xl font-extrabold"><span className="grid h-9 w-9 place-items-center rounded-xl bg-brand text-white"><HeartHandshake size={20}/></span>Impacto Care</Link><Link className="text-sm font-semibold text-brand" to="/">Voltar ao início</Link></div></header><main className="mx-auto max-w-4xl px-6 py-14"><article className="card !p-7 md:!p-12"><p className="text-sm font-semibold uppercase tracking-wide text-brand">Documento público</p><h1 className="mt-3 text-3xl md:text-4xl">{title}</h1><p className="mt-4 leading-7 text-ink/65">{intro}</p><p className="mt-3 text-sm text-ink/45">Última atualização: {updated}</p><div className="mt-10 space-y-9">{children}</div></article></main><footer className="pb-10 text-center text-sm text-ink/50"><Link to="/privacidade">Privacidade</Link><span className="mx-3">•</span><Link to="/termos">Termos de uso</Link></footer></div>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section><h2 className="text-xl">{title}</h2><div className="mt-3 space-y-3 leading-7 text-ink/70">{children}</div></section>}

export function PrivacyPage(){return <LegalPage title="Aviso de Privacidade" intro="Este aviso explica como o Impacto Care trata dados pessoais na plataforma de gestão para profissionais de atendimento domiciliar.">
<Section title="1. Agentes de tratamento e contato"><p>O Impacto Care fornece a infraestrutura tecnológica. Para dados da conta, assinatura, segurança e suporte, a plataforma atua como controladora. O profissional ou organização contratante decide as finalidades dos dados de pacientes, responsáveis e familiares e normalmente atua como controlador; nesse contexto, o Impacto Care atua como operador segundo suas instruções.</p><p>Solicitações podem ser enviadas para <a className="font-semibold text-brand" href={`mailto:${contact}`}>{contact}</a>.</p></Section>
<Section title="2. Dados tratados"><ul className="list-disc space-y-2 pl-6"><li>Cadastro do profissional: nome, CPF, profissão, conselho, telefone, e-mail e endereço.</li><li>Dados de pacientes, responsáveis e familiares, incluindo identificação, contato, endereço, necessidades, condições informadas, medicamentos, alergias e mobilidade.</li><li>Agenda, registros de atendimento, avaliações, informações financeiras, aceite simples e vínculos do portal da família.</li><li>Dados técnicos e de segurança, como horários, ações, IP, navegador, autenticação e falhas.</li><li>Identificadores de assinatura e pagamento. O Impacto Care não armazena os dados completos do cartão.</li></ul></Section>
<Section title="3. Origem e finalidades"><p>Os dados são fornecidos pelo titular, pelo profissional, por responsável ou familiar autorizado, ou por provedores de autenticação, cobrança e operação. São usados para criar e proteger contas, disponibilizar os módulos contratados, enviar mensagens operacionais, processar pagamentos, prestar suporte, manter segurança e auditoria e cumprir obrigações legais.</p></Section>
<Section title="4. Bases legais"><p>Conforme o contexto, o tratamento pode se apoiar em execução de contrato, procedimentos preliminares, obrigação legal, exercício regular de direitos, legítimo interesse, proteção da vida, tutela da saúde por agentes habilitados e consentimento quando adequado. O profissional é responsável por definir e documentar a base aplicável aos dados que insere, especialmente dados pessoais sensíveis.</p></Section>
<Section title="5. Compartilhamento"><p>Dados são compartilhados somente quando necessário com fornecedores de hospedagem e banco de dados, Brevo para e-mails, Google para autenticação, Asaas para pagamentos, Cloudflare para DNS e proteção, e serviços técnicos de rota e CEP. Também poderá haver compartilhamento por obrigação legal, ordem válida ou proteção de direitos e segurança.</p></Section>
<Section title="6. Segurança e retenção"><p>Adotamos autenticação, controle de acesso por perfil e organização, conexões criptografadas, segregação lógica, auditoria, backups e restrição administrativa. Os dados permanecem pelo tempo necessário ao serviço, às obrigações legais e ao exercício de direitos; depois, poderão ser eliminados ou anonimizados, ressalvadas hipóteses legítimas de conservação.</p></Section>
<Section title="7. Direitos dos titulares"><p>Conforme aplicável, o titular pode solicitar confirmação, acesso, correção, informação sobre compartilhamento, anonimização, bloqueio, portabilidade, eliminação e revogação de consentimento. A identidade poderá ser verificada. Para dados inseridos por um profissional, a solicitação deve ser dirigida inicialmente a ele ou à organização responsável, e o Impacto Care prestará o suporte técnico necessário.</p></Section>
<Section title="8. Cookies e armazenamento local"><p>Utilizamos recursos estritamente necessários para autenticação e funcionamento, incluindo armazenamento local do token de acesso. A versão atual não usa publicidade nem rastreamento comportamental. Se isso mudar, este aviso e os controles aplicáveis serão atualizados.</p></Section>
<Section title="9. Alterações"><p>O aviso poderá ser atualizado por mudanças legais, operacionais ou tecnológicas. Alterações relevantes serão comunicadas por meio adequado. Dúvidas e pedidos devem ser enviados para <a className="font-semibold text-brand" href={`mailto:${contact}`}>{contact}</a>.</p></Section>
</LegalPage>}

export function TermsPage(){return <LegalPage title="Termos de Uso" intro="Estes termos regulam o acesso ao Impacto Care. Ao criar uma conta ou utilizar a plataforma, o usuário declara que leu e concorda com estas condições.">
<Section title="1. Serviço"><p>O Impacto Care é uma plataforma de gestão para profissionais de atendimento domiciliar, com cadastro de pacientes e responsáveis, agenda, registros de atendimento, avaliações, rotas, financeiro, portal da família e assinatura. A plataforma não presta serviços assistenciais, não substitui o julgamento profissional e não garante resultados.</p></Section>
<Section title="2. Cadastro"><p>O usuário deve informar dados verdadeiros, manter as credenciais protegidas e comunicar acessos indevidos. É proibido compartilhar conta individual ou usar identidade alheia. O profissional declara possuir habilitações e registros necessários à sua atividade e mantê-los atualizados.</p></Section>
<Section title="3. Uso permitido"><p>O serviço deve ser usado para finalidades lícitas relacionadas à gestão do usuário. É proibido violar direitos, acessar outra organização, explorar vulnerabilidades, inserir código malicioso, sobrecarregar o serviço, revender acesso sem autorização ou tratar dados sem base legal.</p></Section>
<Section title="4. Responsabilidade pelos dados"><p>O profissional responde pelos dados que coleta, insere, corrige, compartilha e exclui, por definir bases legais e por conceder acesso familiar somente a pessoas autorizadas. Formulários enviados à família devem atender a solicitações legítimas e não devem pedir informações excessivas.</p></Section>
<Section title="5. Teste, planos e pagamentos"><p>O teste gratuito vigente dura 30 dias e não exige cartão. Depois, a continuidade poderá depender de assinatura. Os preços atuais são R$ 59,90 no plano mensal e R$ 478,80 no anual, equivalente a R$ 39,90 por mês, sujeitos a atualização mediante comunicação prévia.</p><p>Pagamentos são processados por provedor externo. O não pagamento poderá limitar recursos após o período de tolerância informado ao usuário.</p></Section>
<Section title="6. Segurança e disponibilidade"><p>O usuário deve usar senha forte, proteger seus dispositivos e encerrar sessões compartilhadas. Poderemos bloquear acessos em caso de risco, fraude, violação ou obrigação legal. Podem ocorrer manutenções, falhas de internet e indisponibilidade de fornecedores. O usuário deve manter procedimentos próprios de continuidade para situações urgentes.</p></Section>
<Section title="7. Propriedade intelectual"><p>Marca, interface, código e conteúdos do Impacto Care pertencem aos seus titulares. A assinatura concede direito limitado, revogável e não exclusivo de uso. O usuário mantém direitos sobre seus dados e autoriza somente o processamento necessário ao serviço, segurança e backup.</p></Section>
<Section title="8. Cancelamento"><p>O cancelamento pode ser solicitado pelos canais oficiais. Antes do encerramento, o usuário deve exportar informações necessárias. Dados poderão ser mantidos para obrigações legais, prevenção de fraude e exercício de direitos, conforme o Aviso de Privacidade.</p></Section>
<Section title="9. Limites e contato"><p>Cada parte responde por suas obrigações e pelos danos que causar. O Impacto Care não responde por decisões profissionais, informações incorretas fornecidas pelos usuários, falhas de terceiros ou uso fora das finalidades oferecidas, sem afastar direitos que não possam ser limitados por lei.</p><p>Dúvidas podem ser enviadas para <a className="font-semibold text-brand" href={`mailto:${contact}`}>{contact}</a>. Aplica-se a legislação brasileira, respeitados os direitos do consumidor e as regras legais de competência.</p></Section>
</LegalPage>}
