import {FormEvent,useState} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {useParams} from 'react-router-dom';
import {CalendarCheck,HeartHandshake} from 'lucide-react';
import {api,post,put} from './api';

type Window={weekday:number;start_time:string;end_time:string;is_active:boolean};
type Settings={default_session_duration_minutes:number;windows:Window[]};
const days=['Segunda-feira','Terça-feira','Quarta-feira','Quinta-feira','Sexta-feira','Sábado','Domingo'];
export function AvailabilityPage(){
 const q=useQueryClient(),{data}=useQuery({queryKey:['availability'],queryFn:()=>api<Settings>('/availability')});
 const [message,setMessage]=useState('');const save=useMutation({mutationFn:(body:Settings)=>put<Settings>('/availability',body),onSuccess:()=>{q.invalidateQueries({queryKey:['availability']});setMessage('Disponibilidade salva com sucesso.')},onError:e=>setMessage(e.message)});
 if(!data)return <p>Carregando disponibilidade...</p>;
 const current=Object.fromEntries(data.windows.map(w=>[w.weekday,w]));
 return <section><div className="mb-7"><h1 className="text-3xl">Disponibilidade de atendimento</h1><p className="mt-1 text-ink/55">Defina quando você trabalha e a duração padrão das sessões.</p></div><form className="card max-w-3xl" onSubmit={(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),windows:Window[]=[];days.forEach((_,weekday)=>{if(f.get(`active_${weekday}`))windows.push({weekday,start_time:String(f.get(`start_${weekday}`)),end_time:String(f.get(`end_${weekday}`)),is_active:true})});save.mutate({default_session_duration_minutes:Number(f.get('duration')),windows})}}><label className="block max-w-xs"><span className="label">Tempo médio da sessão (minutos)</span><input className="input" name="duration" type="number" min="15" max="480" step="5" defaultValue={data.default_session_duration_minutes} required/></label><div className="mt-7 space-y-3">{days.map((label,weekday)=>{const row=current[weekday];return <div className="grid items-center gap-3 rounded-xl border border-ink/10 p-3 md:grid-cols-[1fr_120px_120px]" key={label}><label className="flex gap-2 font-semibold"><input type="checkbox" name={`active_${weekday}`} defaultChecked={!!row}/>{label}</label><input aria-label={`Início ${label}`} className="input" name={`start_${weekday}`} type="time" defaultValue={row?.start_time?.slice(0,5)||'08:00'}/><input aria-label={`Fim ${label}`} className="input" name={`end_${weekday}`} type="time" defaultValue={row?.end_time?.slice(0,5)||'18:00'}/></div>})}</div>{message&&<p className="mt-4 text-sm text-brand">{message}</p>}<button className="btn-primary mt-6" disabled={save.isPending}>{save.isPending?'Salvando...':'Salvar disponibilidade'}</button></form></section>
}
type PublicVisit={patient_name:string;professional_name:string;starts_at:string;duration_minutes:number;status:string;patient_response?:string};type Slot={starts_at:string;ends_at:string};
export function PublicAppointmentPage(){
 const {token}=useParams(),q=useQueryClient(),[rescheduling,setRescheduling]=useState(false),[message,setMessage]=useState('');
 const info=useQuery({queryKey:['public-visit',token],queryFn:()=>api<PublicVisit>(`/public/visits/${token}`),retry:false});
 const slots=useQuery({queryKey:['public-slots',token],queryFn:()=>api<Slot[]>(`/public/visits/${token}/available-slots`),enabled:rescheduling});
 const respond=useMutation({mutationFn:(body:{action:string;new_starts_at?:string})=>post<PublicVisit>(`/public/visits/${token}/response`,body),onSuccess:(result)=>{q.setQueryData(['public-visit',token],result);q.invalidateQueries({queryKey:['public-slots',token]});setRescheduling(false);setMessage(result.patient_response==='confirmed'?'Atendimento confirmado.':result.patient_response==='canceled'?'Atendimento desmarcado. O profissional foi avisado.':'Atendimento reagendado. O profissional foi avisado.')},onError:e=>setMessage(e.message)});
 if(info.isLoading)return <Page><p>Carregando agendamento...</p></Page>;if(info.error||!info.data)return <Page><Card title="Link indisponível"><p>Este link é inválido. Solicite um novo link ao profissional.</p></Card></Page>;
 const visit=info.data,canceled=visit.status==='canceled';return <Page><div className="card w-full max-w-2xl !p-8"><div className="flex items-center gap-2 text-xl font-bold"><HeartHandshake className="text-brand"/>Impacto Care</div><div className="mt-7 flex items-center gap-3"><CalendarCheck className="text-brand"/><div><h1 className="text-2xl">Seu atendimento</h1><p className="text-sm text-ink/55">com {visit.professional_name}</p></div></div><div className="my-6 rounded-xl bg-mint p-5"><b>{visit.patient_name}</b><p>{new Date(visit.starts_at).toLocaleString('pt-BR',{dateStyle:'full',timeStyle:'short'})}</p><p className="text-sm">Duração prevista: {visit.duration_minutes} minutos</p></div>{message&&<p className="mb-4 rounded-lg bg-mint p-3 text-sm font-semibold text-brand">{message}</p>}{!canceled&&!rescheduling&&<div className="grid gap-3 sm:grid-cols-3"><button className="btn-primary" onClick={()=>respond.mutate({action:'confirm'})}>Confirmar</button><button className="btn-outline" onClick={()=>setRescheduling(true)}>Reagendar</button><button className="btn-outline text-red-600" onClick={()=>confirm('Deseja realmente desmarcar?')&&respond.mutate({action:'cancel'})}>Desmarcar</button></div>}{rescheduling&&<div><h2 className="mb-3 text-lg">Escolha um horário disponível</h2>{slots.isLoading&&<p>Buscando horários...</p>}<div className="grid max-h-72 gap-2 overflow-auto sm:grid-cols-2">{slots.data?.map(slot=><button className="btn-outline" key={slot.starts_at} onClick={()=>respond.mutate({action:'reschedule',new_starts_at:slot.starts_at})}>{new Date(slot.starts_at).toLocaleString('pt-BR',{weekday:'short',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}</button>)}</div>{slots.data?.length===0&&<p className="text-sm text-ink/55">Não há horários vagos nos próximos dias.</p>}<button className="mt-4 text-sm font-semibold text-brand" onClick={()=>setRescheduling(false)}>Voltar</button></div>}{canceled&&<p className="text-sm text-ink/60">Este atendimento está desmarcado.</p>}</div></Page>
}
function Page({children}:{children:React.ReactNode}){return <main className="grid min-h-screen place-items-center bg-sand p-5">{children}</main>}function Card({title,children}:{title:string;children:React.ReactNode}){return <div className="card max-w-lg"><h1 className="text-2xl">{title}</h1><div className="mt-3">{children}</div></div>}
